//------------------------------------------------------------------------------
// <auto-generated>
// BaseRes.cs
//
// Do not edit directly. This file has been generated by PublicResXFileScriptGenerator v0.7.0.0.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

namespace LxnBase {

    /// <summary>BaseRes resources class</summary>
    [GeneratedCodeAttribute("ResXPublicScriptGenerator", "0.7.0.0")]
    [Resources]
    public static class BaseRes {

        public static readonly string AtoGrid_UpdateRowMsg1 = null;

        public static readonly string AtoGrid_UpdateRowMsg2 = null;

        public static readonly string AutoGrid_ActionNotPermitted_Msg = null;

        public static readonly string AutoGrid_ContinueDelete_Msg = null;

        public static readonly string AutoGrid_DeleteCompletedMsg1 = null;

        public static readonly string AutoGrid_DeleteCompletedMsg2 = null;

        public static readonly string AutoGrid_DeleteCompletedMsg3 = null;

        public static readonly string AutoGrid_DeleteConstrainedFailed_Msg = null;

        public static readonly string AutoGrid_DeleteFailed_Msg = null;

        public static readonly string AutoGrid_DeleteMsg1 = null;

        public static readonly string AutoGrid_DeleteMsg2 = null;

        public static readonly string AutoGrid_DeleteMsg3 = null;

        public static readonly string AutoGrid_DispayMsg = null;

        public static readonly string AutoGrid_EmptyMsg = null;

        public static readonly string AutoGrid_NotDisplay_Msg = null;

        public static readonly string AutoGrid_RefreshData = null;

        public static readonly string AutoGrid_RejectChanges = null;

        public static readonly string AutoGrid_RepeatUpdate = null;

        public static readonly string AutoGrid_ReplaceToAdmin_Msg = null;

        public static readonly string AutoGrid_ResetFilter_Title = null;

        public static readonly string AutoGrid_ReturnToEditing = null;

        public static readonly string AutoGrid_SaveChanges = null;

        public static readonly string AutoGrid_SimpleFilter_Title = null;

        public static readonly string AutoGrid_SuspendUpdate = null;

        public static readonly string AutoGrid_UnsavedChangesMsg = null;

        public static readonly string AutoList_AutoCommit = null;

        public static readonly string Cancel = null;

        public static readonly string Cancel_Lower = null;

        public static readonly string Caption_Separator = null;

        public static readonly string Clear = null;

        public static readonly string Close = null;

        public static readonly string Confirmation = null;

        public static readonly string Copy = null;

        public static readonly string Copy_Lower = null;

        public static readonly string Created = null;

        public static readonly string CreateItem = null;

        public static readonly string CreateItem_Lower = null;

        public static readonly string CreateObjectMsg = null;

        public static readonly string Creation = null;

        public static readonly string Deleted = null;

        public static readonly string Delete_Confirmation = null;

        public static readonly string Edit = null;

        public static readonly string Editing = null;

        public static readonly string Edit_Lower = null;

        public static readonly string Error = null;

        public static readonly string Export_Action = null;

        public static readonly string Export_All = null;

        public static readonly string Export_ExceptSelection = null;

        public static readonly string Export_Selection = null;

        public static readonly string FilterOperator_Contains = null;

        public static readonly string FilterOperator_EndsWith = null;

        public static readonly string FilterOperator_Equals = null;

        public static readonly string FilterOperator_Greater = null;

        public static readonly string FilterOperator_GreaterOrEquals = null;

        public static readonly string FilterOperator_IsIn = null;

        public static readonly string FilterOperator_IsNull = null;

        public static readonly string FilterOperator_Less = null;

        public static readonly string FilterOperator_LessOrEquals = null;

        public static readonly string FilterOperator_None = null;

        public static readonly string FilterOperator_StartsWith = null;

        public static readonly string Filter_AfterDate = null;

        public static readonly string Filter_BeforeDate = null;

        public static readonly string Filter_Conjunction = null;

        public static readonly string Filter_False = null;

        public static readonly string Filter_GeneralFilterMsg = null;

        public static readonly string Filter_Not = null;

        public static readonly string Filter_OnDate = null;

        public static readonly string Filter_Title = null;

        public static readonly string Filter_True = null;

        public static readonly string List = null;

        public static readonly string Loading = null;

        public static readonly string Messages_Title = null;

        public static readonly string NoData_Text = null;

        public static readonly string PropertyFilterCondition_Not = null;

        public static readonly string Remove = null;

        public static readonly string Remove_Lower = null;

        public static readonly string Replace = null;

        public static readonly string ReplaceDelete = null;

        public static readonly string ReplaceForm_DeleteAfterReplace = null;

        public static readonly string ReplaceForm_DependentObjects = null;

        public static readonly string ReplaceForm_ObjectForReplace = null;

        public static readonly string ReplaceForm_ReplaceComplete_Msg = null;

        public static readonly string ReplaceForm_ReplacingObject = null;

        public static readonly string Salutation = null;

        public static readonly string Salutation_Text_List = null;

        public static readonly string Save = null;

        public static readonly string SaveChenges_Msg = null;

        public static readonly string SaveObjectValidationErrorMsg = null;

        public static readonly string Save_Lower = null;

        public static readonly string Select_Lower = null;

        public static readonly string UnknownError = null;

        public static readonly string UnreadMessageCount_Msg1 = null;

        public static readonly string UnreadMessageCount_Msg2 = null;

        public static readonly string UnreadMessageCount_Msg3 = null;

        public static readonly string Updated = null;

        public static readonly string UpdateObjectMsg = null;

        public static readonly string ValiadationStatusHideError_Msg = null;

        public static readonly string ValiadationStatusSowError_Msg = null;

        public static readonly string View = null;

        public static readonly string Warning = null;

        public static readonly string WebServiceAborted = null;

        public static readonly string WebServiceFailed = null;

        public static readonly string WebServiceFailedNoMsg = null;

        public static readonly string WebServiceInvalidJsonWrapper = null;

        public static readonly string WebServiceParseError = null;

        public static readonly string WebServiceResponse_Error_Msg = null;

        public static readonly string WebServiceResponse_Error_Title = null;

        public static readonly string WebServiceTimedOut = null;
    }
}
