//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxena.Travel.Persey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luxena.Travel.Persey.ReportRes", typeof(ReportRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to р/р 26005601362575 в АТ «ОТП Банк», МФО 300528, ЕДРПОУ 37615909.
        /// </summary>
        public static string TicketPrinter_Footer1 {
            get {
                return ResourceManager.GetString("TicketPrinter_Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОВ «Персей Тревел»
        ///01054, Київ
        ///вул. Кіквідзе 6, оф.22
        ///тел. 38 044 360 30 00
        ///тел. 38 044 360 33 00
        ///www.persey.travel.
        /// </summary>
        public static string TicketPrinter_Header1 {
            get {
                return ResourceManager.GetString("TicketPrinter_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Persey Travel» LTD 
        ///01034, Kyiv
        ///6 Kikvidze str, of.22
        ///tel. 38 044 360 30 00
        ///tel. 38 044 360 33 00  
        ///sales@persey.travel.
        /// </summary>
        public static string TicketPrinter_Header2 {
            get {
                return ResourceManager.GetString("TicketPrinter_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static\templates\ticket\persey_ticket_logo1.png.
        /// </summary>
        public static string TicketPrinter_LogoPath1 {
            get {
                return ResourceManager.GetString("TicketPrinter_LogoPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static\templates\ticket\persey_ticket_logo2.png.
        /// </summary>
        public static string TicketPrinter_LogoPath2 {
            get {
                return ResourceManager.GetString("TicketPrinter_LogoPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static\templates\ticket\persey_ticket_logo3.png.
        /// </summary>
        public static string TicketPrinter_LogoPath3 {
            get {
                return ResourceManager.GetString("TicketPrinter_LogoPath3", resourceCulture);
            }
        }
    }
}
