//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxena.Base {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luxena.Base.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав для данного действия. Если вам необходимы права, обратитесь к администратору системы.
        /// </summary>
        public static string CreateOperationDenied_Msg {
            get {
                return ResourceManager.GetString("CreateOperationDenied_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав для данного действия. Если вам необходимы права, обратитесь к администратору системы.
        /// </summary>
        public static string DeleteOperationDenied_Msg {
            get {
                return ResourceManager.GetString("DeleteOperationDenied_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string Entity_CreatedBy {
            get {
                return ResourceManager.GetString("Entity_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string Entity_CreatedOn {
            get {
                return ResourceManager.GetString("Entity_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string Entity_ModifiedBy {
            get {
                return ResourceManager.GetString("Entity_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string Entity_ModifiedOn {
            get {
                return ResourceManager.GetString("Entity_ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав для данного действия. Если вам необходимы права, обратитесь к администратору системы.
        /// </summary>
        public static string ListOperationDenied_Msg {
            get {
                return ResourceManager.GetString("ListOperationDenied_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        public static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Modification_Author {
            get {
                return ResourceManager.GetString("Modification_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Log.
        /// </summary>
        public static string Modification_Caption_List {
            get {
                return ResourceManager.GetString("Modification_Caption_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Modification_Comment {
            get {
                return ResourceManager.GetString("Modification_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Modification_DisplayType {
            get {
                return ResourceManager.GetString("Modification_DisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        public static string Modification_Instance {
            get {
                return ResourceManager.GetString("Modification_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Id.
        /// </summary>
        public static string Modification_InstanceId {
            get {
                return ResourceManager.GetString("Modification_InstanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp.
        /// </summary>
        public static string Modification_TimeStamp {
            get {
                return ResourceManager.GetString("Modification_TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Modification_Type {
            get {
                return ResourceManager.GetString("Modification_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ModificationItem {
            get {
                return ResourceManager.GetString("ModificationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string ModificationItem_Attribute {
            get {
                return ResourceManager.GetString("ModificationItem_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ModificationItem_Caption_List {
            get {
                return ResourceManager.GetString("ModificationItem_Caption_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        public static string ModificationItem_NewValue {
            get {
                return ResourceManager.GetString("ModificationItem_NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ModificationType_Create {
            get {
                return ResourceManager.GetString("ModificationType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ModificationType_Delete {
            get {
                return ResourceManager.GetString("ModificationType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ModificationType_Update {
            get {
                return ResourceManager.GetString("ModificationType_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав для данного действия. Если вам необходимы права, обратитесь к администратору системы.
        /// </summary>
        public static string ReplaceOperationDenied_Msg {
            get {
                return ResourceManager.GetString("ReplaceOperationDenied_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав для данного действия. Если вам необходимы права, обратитесь к администратору системы.
        /// </summary>
        public static string UpdateOperationDenied_Msg {
            get {
                return ResourceManager.GetString("UpdateOperationDenied_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав для данного действия. Если вам необходимы права, обратитесь к администратору системы.
        /// </summary>
        public static string ViewOperationDenied_Msg {
            get {
                return ResourceManager.GetString("ViewOperationDenied_Msg", resourceCulture);
            }
        }
    }
}
