//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxena.Travel.AtlasTour {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luxena.Travel.AtlasTour.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After departure:.
        /// </summary>
        internal static string AfterDeparture_eng {
            get {
                return ResourceManager.GetString("AfterDeparture_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Після відльоту:.
        /// </summary>
        internal static string AfterDeparture_ua {
            get {
                return ResourceManager.GetString("AfterDeparture_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency office:.
        /// </summary>
        internal static string AgencyOffice_eng {
            get {
                return ResourceManager.GetString("AgencyOffice_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Офіс агентства:.
        /// </summary>
        internal static string AgencyOffice_ua {
            get {
                return ResourceManager.GetString("AgencyOffice_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent:.
        /// </summary>
        internal static string Agent_eng {
            get {
                return ResourceManager.GetString("Agent_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агент:.
        /// </summary>
        internal static string Agent_ua {
            get {
                return ResourceManager.GetString("Agent_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREEMENT.
        /// </summary>
        internal static string Agreement_eng {
            get {
                return ResourceManager.GetString("Agreement_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОГОДЖЕННЯ.
        /// </summary>
        internal static string Agreement_ua {
            get {
                return ResourceManager.GetString("Agreement_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing airline:.
        /// </summary>
        internal static string Airline_eng {
            get {
                return ResourceManager.GetString("Airline_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авіакомпанія-власник квитка:.
        /// </summary>
        internal static string Airline_ua {
            get {
                return ResourceManager.GetString("Airline_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Arrival.
        /// </summary>
        internal static string Arrival_eng {
            get {
                return ResourceManager.GetString("Arrival_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибуття.
        /// </summary>
        internal static string Arrival_ua {
            get {
                return ResourceManager.GetString("Arrival_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before departure:.
        /// </summary>
        internal static string BeforeDeparture_eng {
            get {
                return ResourceManager.GetString("BeforeDeparture_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До відльоту:.
        /// </summary>
        internal static string BeforeDeparture_ua {
            get {
                return ResourceManager.GetString("BeforeDeparture_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking ref:.
        /// </summary>
        internal static string Booking_ref_eng {
            get {
                return ResourceManager.GetString("Booking_ref_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код бронювання:.
        /// </summary>
        internal static string Booking_ref_ua {
            get {
                return ResourceManager.GetString("Booking_ref_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking reference:.
        /// </summary>
        internal static string BookingNumber_eng {
            get {
                return ResourceManager.GetString("BookingNumber_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер бронювання:.
        /// </summary>
        internal static string BookingNumber_ua {
            get {
                return ResourceManager.GetString("BookingNumber_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATION.
        /// </summary>
        internal static string Calculation_eng {
            get {
                return ResourceManager.GetString("Calculation_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РОЗРАХУНОК ВАРТОСТI.
        /// </summary>
        internal static string Calculation_ua {
            get {
                return ResourceManager.GetString("Calculation_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car rental.
        /// </summary>
        internal static string CarRental_eng {
            get {
                return ResourceManager.GetString("CarRental_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прокат авто.
        /// </summary>
        internal static string CarRental_ua {
            get {
                return ResourceManager.GetString("CarRental_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заборонено / DENIED.
        /// </summary>
        internal static string ChangesNotAllowed {
            get {
                return ResourceManager.GetString("ChangesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штраф / CHARGE.
        /// </summary>
        internal static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Class.
        /// </summary>
        internal static string Class_eng {
            get {
                return ResourceManager.GetString("Class_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клас.
        /// </summary>
        internal static string Class_ua {
            get {
                return ResourceManager.GetString("Class_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAH.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Data_eng {
            get {
                return ResourceManager.GetString("Data_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Date change.
        /// </summary>
        internal static string Date_change_eng {
            get {
                return ResourceManager.GetString("Date_change_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна дати.
        /// </summary>
        internal static string Date_change_ua {
            get {
                return ResourceManager.GetString("Date_change_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Date:.
        /// </summary>
        internal static string Date_discharge_eng {
            get {
                return ResourceManager.GetString("Date_discharge_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата виписки:.
        /// </summary>
        internal static string Date_discharge_ua {
            get {
                return ResourceManager.GetString("Date_discharge_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Date:.
        /// </summary>
        internal static string Date_eng {
            get {
                return ResourceManager.GetString("Date_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата виписки:.
        /// </summary>
        internal static string Date_ua {
            get {
                return ResourceManager.GetString("Date_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date change.
        /// </summary>
        internal static string DateChange_eng {
            get {
                return ResourceManager.GetString("DateChange_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна дати.
        /// </summary>
        internal static string DateChange_ua {
            get {
                return ResourceManager.GetString("DateChange_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВИЛIТ: .
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Departure.
        /// </summary>
        internal static string Departure_eng {
            get {
                return ResourceManager.GetString("Departure_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вiдльот.
        /// </summary>
        internal static string Departure_ua {
            get {
                return ResourceManager.GetString("Departure_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELECTRONIC TICKET.
        /// </summary>
        internal static string ElectronicTicket_eng {
            get {
                return ResourceManager.GetString("ElectronicTicket_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕЛЕКТРОНИЙ КВИТОК.
        /// </summary>
        internal static string ElectronicTicket_ua {
            get {
                return ResourceManager.GetString("ElectronicTicket_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsement.
        /// </summary>
        internal static string Endorsement {
            get {
                return ResourceManager.GetString("Endorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiarized with main terms of transportation, notices, fare rules.
        /// </summary>
        internal static string Familiarize_Msg1_eng {
            get {
                return ResourceManager.GetString("Familiarize_Msg1_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З істотними умовами перевезення, нотатками, правилами тарифу.
        /// </summary>
        internal static string Familiarize_Msg1_ua {
            get {
                return ResourceManager.GetString("Familiarize_Msg1_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and passport and visa regulations.
        /// </summary>
        internal static string Familiarize_Msg2_eng {
            get {
                return ResourceManager.GetString("Familiarize_Msg2_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to та паспортно-візовим режимом ознайомлений (-а).
        /// </summary>
        internal static string Familiarize_Msg2_ua {
            get {
                return ResourceManager.GetString("Familiarize_Msg2_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equiv. fare, UAH:.
        /// </summary>
        internal static string Fare_eng {
            get {
                return ResourceManager.GetString("Fare_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тариф, грн:.
        /// </summary>
        internal static string Fare_ua {
            get {
                return ResourceManager.GetString("Fare_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такси детальніше, ГРН:.
        /// </summary>
        internal static string FeesDetails {
            get {
                return ResourceManager.GetString("FeesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Flight.
        /// </summary>
        internal static string Flight_eng {
            get {
                return ResourceManager.GetString("Flight_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейс.
        /// </summary>
        internal static string Flight_ua {
            get {
                return ResourceManager.GetString("Flight_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flighttime.
        /// </summary>
        internal static string Flighttime_eng {
            get {
                return ResourceManager.GetString("Flighttime_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час у польоті.
        /// </summary>
        internal static string Flighttime_ua {
            get {
                return ResourceManager.GetString("Flighttime_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FQTV №:.
        /// </summary>
        internal static string FQTV {
            get {
                return ResourceManager.GetString("FQTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels reservation.
        /// </summary>
        internal static string HotelsReservation_eng {
            get {
                return ResourceManager.GetString("HotelsReservation_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронювання готелів.
        /// </summary>
        internal static string HotelsReservation_ua {
            get {
                return ResourceManager.GetString("HotelsReservation_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IATA №.
        /// </summary>
        internal static string IataNumber {
            get {
                return ResourceManager.GetString("IataNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance of travelers.
        /// </summary>
        internal static string Insurance_eng {
            get {
                return ResourceManager.GetString("Insurance_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страхування подорожуючих.
        /// </summary>
        internal static string Insurance_ua {
            get {
                return ResourceManager.GetString("Insurance_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing airline:.
        /// </summary>
        internal static string Issuing_airline_eng {
            get {
                return ResourceManager.GetString("Issuing_airline_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевізник:.
        /// </summary>
        internal static string Issuing_airline_ua {
            get {
                return ResourceManager.GetString("Issuing_airline_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITINERARY.
        /// </summary>
        internal static string Itinerary_eng {
            get {
                return ResourceManager.GetString("Itinerary_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МАРШРУТ.
        /// </summary>
        internal static string Itinerary_ua {
            get {
                return ResourceManager.GetString("Itinerary_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lastcheck-in.
        /// </summary>
        internal static string Lastcheck_in_eng {
            get {
                return ResourceManager.GetString("Lastcheck_in_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрацiя.
        /// </summary>
        internal static string Lastcheck_in_ua {
            get {
                return ResourceManager.GetString("Lastcheck_in_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Luggage seat.
        /// </summary>
        internal static string Luggage_seat_eng {
            get {
                return ResourceManager.GetString("Luggage_seat_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Багаж.
        /// </summary>
        internal static string Luggage_seat_ua {
            get {
                return ResourceManager.GetString("Luggage_seat_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Meals.
        /// </summary>
        internal static string Meals_eng {
            get {
                return ResourceManager.GetString("Meals_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Харчування.
        /// </summary>
        internal static string Meals_ua {
            get {
                return ResourceManager.GetString("Meals_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /No-show.
        /// </summary>
        internal static string No_show_eng {
            get {
                return ResourceManager.GetString("No_show_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нєявка на peєcтpацiю.
        /// </summary>
        internal static string No_show_ua {
            get {
                return ResourceManager.GetString("No_show_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без штрафу / NO CHARGE.
        /// </summary>
        internal static string NoCharge {
            get {
                return ResourceManager.GetString("NoCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-show.
        /// </summary>
        internal static string NoShow_eng {
            get {
                return ResourceManager.GetString("NoShow_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неявка на реєстрацію.
        /// </summary>
        internal static string NoShow_ua {
            get {
                return ResourceManager.GetString("NoShow_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTICES.
        /// </summary>
        internal static string Noties_eng {
            get {
                return ResourceManager.GetString("Noties_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARRIAGE AND OTHER SERVICES PROVIDED BY THE CARRIER ARE SUBJECT TO CONDITIONS OF CARRIAGE, WHICH ARE HEREBY INCORPORATED BY REFERENCE. THESE CONDITIONS MAY BE OBTAINED FROM THE ISSUING CARRIER.   THE ITINERARY/RECEIPT CONSTITUTES THE &apos;PASSENGER TICKET&apos; FOR THE PURPOSES OF ARTICLE 3 OF THE WARSAW CONVENTION, EXCEPT WHERE THE CARRIER DELIVERS TO THE PASSENGER ANOTHER DOCUMENT COMPLYING WITH THE REQUIREMENTS OF ARTICLE 3.    IF THE PASSENGER&apos;S JOURNEY INVOLVES AN ULTIMATE DESTINATION OR STOP IN A COUNTRY OTHER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Noties_Msg_eng {
            get {
                return ResourceManager.GetString("Noties_Msg_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЕРЕВЕЗЕННЯ ТА ІНШІ ПОСЛУГИ НАДАНІ ПЕРЕВІЗНИКОМ РЕГУЛЮЮТЬСЯ УМОВАМИ ПЕРЕВЕЗЕННЯ, ЩО НАДАНІ ТУТ ДЛЯ ДОВІДКИ. ЦІ УМОВИ МОЖУТЬ БУТИ ОТРИМАНІ У ПЕРЕВІЗНИКА – ВЛАСНИКА КВИТКА.   МАРШРУТ/КВИТАНЦІЯ ЗАМІНЮЮТЬ СОБОЙ ПАСАЖИРСЬКИЙ КВИТОК ЗГІДНО СТАТТІ 3 ВАРШАВСЬКОЇ КОНВЕНЦІЇ, КРІМ ТИХ ВИПАДКІВ, КОЛИ ПЕРЕВІЗНИК НАДАЄ ПАСАЖИРАМ ІНШИЙ ДОКУМЕНТ ЩО ВІДПОВІДАЄ ВИМОГАМ СТАТТІ 3   ПАСАЖИРИ, ПЕРЕВЕЗЕННЯ ЯКИХ МАЄ ПУНКТ ПРИЗНАЧЕННЯ АБО ЗУПИНКИ НЕ В КРАЇНІ ВИЛЬОТУ, ПОВІДОМЛЯЮТЬСЯ ПРО ТЕ, ЩО ВАРШАВСЬКА КОНВЕНЦІЯ МОЖЕ БУТИ ЗАСТОСОВ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Noties_Msg_ua {
            get {
                return ResourceManager.GetString("Noties_Msg_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НОТАТКИ.
        /// </summary>
        internal static string Noties_ua {
            get {
                return ResourceManager.GetString("Noties_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number:.
        /// </summary>
        internal static string Number_eng {
            get {
                return ResourceManager.GetString("Number_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер квитка:.
        /// </summary>
        internal static string Number_ua {
            get {
                return ResourceManager.GetString("Number_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONALLY FOR YOUR CONVENIENCE.
        /// </summary>
        internal static string Options_eng {
            get {
                return ResourceManager.GetString("Options_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОДАТКОВО ДЛЯ ВАШОЇ ЗРУЧНОСТІ.
        /// </summary>
        internal static string Options_ua {
            get {
                return ResourceManager.GetString("Options_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Passenger_eng {
            get {
                return ResourceManager.GetString("Passenger_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пасажир:.
        /// </summary>
        internal static string Passenger_ua {
            get {
                return ResourceManager.GetString("Passenger_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport №:.
        /// </summary>
        internal static string Passport_en {
            get {
                return ResourceManager.GetString("Passport_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паспорт №:.
        /// </summary>
        internal static string Passport_ua {
            get {
                return ResourceManager.GetString("Passport_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENALTIES.
        /// </summary>
        internal static string Penalties_eng {
            get {
                return ResourceManager.GetString("Penalties_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ШТРАФНI САНКЦIЇ.
        /// </summary>
        internal static string Penalties_ua {
            get {
                return ResourceManager.GetString("Penalties_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string Refund_eng {
            get {
                return ResourceManager.GetString("Refund_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернення.
        /// </summary>
        internal static string Refund_ua {
            get {
                return ResourceManager.GetString("Refund_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без штрафу / FULL REF.
        /// </summary>
        internal static string RefundNoCharge {
            get {
                return ResourceManager.GetString("RefundNoCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не повертається / NON REF.
        /// </summary>
        internal static string RefundNotAllowed {
            get {
                return ResourceManager.GetString("RefundNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сертифікат на право продажу авіаційних перевезень  № АП0069    Air services sale certificate.
        /// </summary>
        internal static string SaleCertificate {
            get {
                return ResourceManager.GetString("SaleCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приліт/Arrival.
        /// </summary>
        internal static string Segment_ArrivalPlace {
            get {
                return ResourceManager.GetString("Segment_ArrivalPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибуття/
        ///Arrival.
        /// </summary>
        internal static string Segment_ArrivelTime {
            get {
                return ResourceManager.GetString("Segment_ArrivelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація/Last check-in.
        /// </summary>
        internal static string Segment_CheckIn {
            get {
                return ResourceManager.GetString("Segment_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата/Date.
        /// </summary>
        internal static string Segment_Date {
            get {
                return ResourceManager.GetString("Segment_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відліт/Departure.
        /// </summary>
        internal static string Segment_DeparturePlace {
            get {
                return ResourceManager.GetString("Segment_DeparturePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправлення/Departure.
        /// </summary>
        internal static string Segment_DepartureTime {
            get {
                return ResourceManager.GetString("Segment_DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейс/Flight.
        /// </summary>
        internal static string Segment_Flight {
            get {
                return ResourceManager.GetString("Segment_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата  відльоту / Flight date.
        /// </summary>
        internal static string Segment_FlightDate {
            get {
                return ResourceManager.GetString("Segment_FlightDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час у польоті/
        ///Flight time.
        /// </summary>
        internal static string Segment_FlightTime {
            get {
                return ResourceManager.GetString("Segment_FlightTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxena Software Company © 2001-{0}.
        /// </summary>
        internal static string Segment_LuxenaCopyright {
            get {
                return ResourceManager.GetString("Segment_LuxenaCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Харчування /
        ///Meals.
        /// </summary>
        internal static string Segment_Meal {
            get {
                return ResourceManager.GetString("Segment_Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Багаж /
        ///Luggage
        ///Місце / Seat.
        /// </summary>
        internal static string Segment_Seat {
            get {
                return ResourceManager.GetString("Segment_Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMINAL.
        /// </summary>
        internal static string Segment_Terminal {
            get {
                return ResourceManager.GetString("Segment_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс / Class.
        /// </summary>
        internal static string ServiceClass {
            get {
                return ResourceManager.GetString("ServiceClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency service fee is not subject for refund !.
        /// </summary>
        internal static string ServiceFee_Msg_eng {
            get {
                return ResourceManager.GetString("ServiceFee_Msg_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервісний збір агентства не підлягає поверненню !.
        /// </summary>
        internal static string ServiceFee_Msg_ua {
            get {
                return ResourceManager.GetString("ServiceFee_Msg_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature:.
        /// </summary>
        internal static string Signature_eng {
            get {
                return ResourceManager.GetString("Signature_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підпис:.
        /// </summary>
        internal static string Signature_ua {
            get {
                return ResourceManager.GetString("Signature_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes, UAH:.
        /// </summary>
        internal static string Taxes_eng {
            get {
                return ResourceManager.GetString("Taxes_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аеропортові та інші збори, грн:.
        /// </summary>
        internal static string Taxes_ua {
            get {
                return ResourceManager.GetString("Taxes_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE TICKET IS NOT VALID IF THE FIRST COUPON HAS NOT BEEN USED AND WILL NOT BE HONORED IF ALL THE COUPONS ARE NOT USED IN THE SEQUENCE PROVIDED IN THE TICKET.
        /// </summary>
        internal static string Ticket_Not_Valid_en {
            get {
                return ResourceManager.GetString("Ticket_Not_Valid_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КВИТОК НЕ Є ДІЙСНИМ У РАЗІ ПОРУШЕННЯ ПОСЛІДОВНОСТІ ВИКОРИСТАННЯ ПОЛЬОТНИХ КУПОНІВ.
        /// </summary>
        internal static string Ticket_Not_Valid_ua {
            get {
                return ResourceManager.GetString("Ticket_Not_Valid_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number:.
        /// </summary>
        internal static string Ticket_number_eng {
            get {
                return ResourceManager.GetString("Ticket_number_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер квитка:.
        /// </summary>
        internal static string Ticket_number_ua {
            get {
                return ResourceManager.GetString("Ticket_number_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заборонено / DENIED.
        /// </summary>
        internal static string TicketPrinter_ChangesNotAllowed {
            get {
                return ResourceManager.GetString("TicketPrinter_ChangesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штраф / CHARGE.
        /// </summary>
        internal static string TicketPrinter_Charge {
            get {
                return ResourceManager.GetString("TicketPrinter_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если выполняется перевозка, в которой место окончательного назначения или остановка находятся не в стране отправления, к такой перевозке могут применяться положения Варшавской конвенции и эта Конвенция определяет и в большинстве случаев ограничивает ответственность перевозчиков в случае утери или повреждения товаров..
        /// </summary>
        internal static string TicketPrinter_Footer {
            get {
                return ResourceManager.GetString("TicketPrinter_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без штрафу / NO CHARGE.
        /// </summary>
        internal static string TicketPrinter_NoCharge {
            get {
                return ResourceManager.GetString("TicketPrinter_NoCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без штрафу / FULL REF.
        /// </summary>
        internal static string TicketPrinter_RefundNoCharge {
            get {
                return ResourceManager.GetString("TicketPrinter_RefundNoCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не повертається / NON REF.
        /// </summary>
        internal static string TicketPrinter_RefundNotAllowed {
            get {
                return ResourceManager.GetString("TicketPrinter_RefundNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВИЛІТ:.
        /// </summary>
        internal static string TicketPrinter_SegmentCaption {
            get {
                return ResourceManager.GetString("TicketPrinter_SegmentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Термінал.
        /// </summary>
        internal static string TicketPrinter_Terminal {
            get {
                return ResourceManager.GetString("TicketPrinter_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total, UAH.
        /// </summary>
        internal static string Total_eng {
            get {
                return ResourceManager.GetString("Total_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разом, грн:.
        /// </summary>
        internal static string Total_ua {
            get {
                return ResourceManager.GetString("Total_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour code.
        /// </summary>
        internal static string TourCode {
            get {
                return ResourceManager.GetString("TourCode", resourceCulture);
            }
        }
    }
}
