//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxena.Travel.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luxena.Travel.Tests.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Александра Яковишин.
        /// </summary>
        internal static string AgentReport_AgentName {
            get {
                return ResourceManager.GetString("AgentReport_AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Білетів світ.
        /// </summary>
        internal static string AgentReport_CompanyName {
            get {
                return ResourceManager.GetString("AgentReport_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- TST RLR ---                                                                 
        ///RP/LEDR2212Y/LEDR2212Y            FV/SU   2JUL12/0259Z   7WDYSI                 
        ///  1.DOVZHIK/NADEZHDA MRS                                                        
        ///  2  FV 344 Q 01JUL 7 MMKLED HK1          2200 2355   *1A/E*                    
        ///  3 AP LED 89112876220-M                                                        
        ///  4 AP LED + 7 - 800- 333-53-66                                                 
        ///  5 TK OK20JUN/MOWR2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirBufferTicket1_1 {
            get {
                return ResourceManager.GetString("AirBufferTicket1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TST00001     LEDR2232Z DN/20JUN I 0 LD 23JUN12 OD MMKLED SI                     
        ///T-                                                                              
        ///FXP                                                                             
        ///   1.DOVZHIK/NADEZHDA MRS                                                       
        /// 1   MMK FV  344 Q 01JUL 2200  OK QPXOW           01JUL01JUL 20K                
        ///	 LED                                                                        
        ///FARE  F RUB       5400  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirBufferTicket1_2 {
            get {
                return ResourceManager.GetString("AirBufferTicket1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7D;;247;1800093986;1A1326991;001001
        ///AMD 1803203094;1/1;              
        ///GW3671466;1A1326991;IEV1A0985;AIR
        ///MUC1A 75I2K4016;0101;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;BA NOSYNC
        ///B-TTM
        ///C-7906/ 2710YDSU-2710YDSU-M---
        ///D-130118;130118;130118
        ///U-001X;002OJFK;NEW YORK JFK     ;LHR;LONDON LHR       ;BA    0174 Q Q 19FEB1855 0700 20FEB;OK01;HK01;M ;0;777;;;;7 ;;ET;0705 ;N;;3444;;US;GB;5 
        ///U-002X;003OLHR;LONDON LHR       ;KBP;KIEV BORYSPIL    ;BA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirEmd1 {
            get {
                return ResourceManager.GetString("AirEmd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7M;;247;0700027759;GW3670495;001001
        ///AMD 0700007409;1/1;              
        ///GW3670922;GW3670495;IEVU23561;AIR
        ///MUC1A YQV5WF100;0101;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;VV YQV5WF
        ///B-TTM
        ///C-7906/ 1962VZSU-1717LSSU-M---
        ///D-080131;080207;080207
        ///MCO449;004VV;8702;AEROSVIT AIRLINES;IEV;TO-AEROSVIT AIRLINES;AT-KIEV;07FEB;M;A;PTA;**-;;F;UAH     101.00;N;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;UAH     101.00;;;;;;;UAH     101.00;;;; ;P1
        ///I-001;01KHONIN/DMI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirMco1 {
            get {
                return ResourceManager.GetString("AirMco1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7M;;247;1500007362;1A1131927;001001
        ///AMD 1500009949;1/1;              
        ///GW3671313;1A1131927;IEVU22118;AIR
        ///MUC1A 335LNS013;0303;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;SU GUIAQC
        ///B-TTM
        ///C-7906/ 0007OPSU-0004ADSU-M---
        ///D-070730;070815;070815
        ///MCO054;005SU;5552;AEROFLOT;MOW;TO-AEROFLOT;AT-MOSCOW;24AUG;M;A;PENALTY FOR REFUND TKT555-1777195244;**-;;F;UAH     143.55;N;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;UAH     143.55;;;;;;;UAH     143.55;;;; ;P1
        ///M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirMco2 {
            get {
                return ResourceManager.GetString("AirMco2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7M;;247;2400246272;1A1131927;001001
        ///AMD 2400006806;1/1;              
        ///GW3671316;1A1131927;IEVU22118;AIR
        ///MUC1A 29DCTX004;0101;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;SU MASFHO
        ///B-TTM
        ///C-7906/ 0002ABSU-0002ABSU-M---
        ///D-070424;070424;070424
        ///MCO019;003SU;5552;AEROFLOT;ATH;TO-AEROFLOT;AT-ATHENS;27APR;M;A;PTA INCL TAX;**-;;F;EUR     365.00;N;UAH    2499.00; UAH   137.00YQ   ; UAH   150.70GR   ; UAH    79.40WP   ; UAH    22.70WQ   ; UAH     6. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirMco3 {
            get {
                return ResourceManager.GetString("AirMco3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7M;;242;1800087253;1A1073783;001001
        ///AMD 1800016281;1/1;              
        ///ST182176;1A1073783
        ///MUC1A 3PUITF052;0101;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;AF 23IONV;BA AJIRPK
        ///B-TTM
        ///C-7906/ 5555LESU-1111AASU-M---
        ///D-070712;070718;070718
        ///MCO167;007BA;1256;BRITISH AIRWAYS;IEV;TO-BRITISH AIRWAYS;AT-KIEV;18JUL;M;A;GOOD FOR REFUND OR AIR TRANSPORTATION;**-;;R;UAH    3636.00;N;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;UAH       0.00;;;125-1777469348;;;;UAH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirMco4 {
            get {
                return ResourceManager.GetString("AirMco4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7M;;224;0300002440;1A1073783;001001
        ///AMD 0300020513;1/1;              
        ///ST182176;1A1073783
        ///MUC1A ZLL4KF020;1601;QLHLH0564;;IEVLH0102;72390975;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;LH NEHMR 
        ///B-TTM
        ///C-7906/ 1000APPD-1111AASU----
        ///D-070920;071003;071003
        ///MCO174;021LH;2203;LUFTHANSA;IEV;TO-LUFTHANSA;AT-KIEV;03OCT;M;A;DEPOSIT FOR GROUP;**-;;F;UAH    2020.00;N;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;UAH    2020.00;;;;;;;UAH    2020.00;;;; ;P1
        ///I-GRP16TELEHAUSE/LISD
        ///I-004;01FOKIN/L MR;;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirMco5 {
            get {
                return ResourceManager.GetString("AirMco5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7M;;233;1700026408;GW3670821;001001
        ///AMD 1700010053;1/1;              
        ///GW3671292;GW3670821
        ///MUC1A ZZND6N022;0101;DOKC32530;72320942;DOKC32530;72320942;DOKC32530;72320942;DOKC32530;72320942;;;;;;;;;;;;;;;;;;;;;;OS H0N8W 
        ///B-TTM
        ///C-7906/ 1234YLSU-0001AASU-M---
        ///D-080122;080417;080417
        ///MCO074;006OS;2575;AUSTRIAN;DOK;TO-AUSTRIAN;AT-DONETSK;20APR;M;A;PENALTY FOR CHNG DATE USD80;**-;;F;UAH     404.00;N;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;UAH     404.00;;;;;;;UAH     404.00;;;; ;P1
        ///MCO083;007OS;2575;AUSTR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirMco6 {
            get {
                return ResourceManager.GetString("AirMco6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;RF;;190;2400015605;GW3670495;001001
        ///AMD 2400018165;1/1;    24MAR;ZXSU
        ///GW3670923;GW3670495
        ///MUC1A          ;  01;IEVU23561;72320441;;;;;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;
        ///B-TRFP
        ///C-7906/ 1234ZXSU-1234ZXSU----
        ///D-090324;090324;090324
        ///RFDF;20MAR09;I;UAH4002.00;0.00;4002.00;;;1000.50;;;XT11.50;3013.00;22MAR09
        ///KRF ;QUAH11.50    RU   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        ///I-001;01GOLOVKO/SERGIY MR;;;;
        ///T-E555-3324622050
        ///R-555-3324622050;24MAR09
        ///SACC55578VC6JJOQ4
        ///FM5.00P
        ///FPINVOICE/UAH3013.00
        ///END [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirRefund1 {
            get {
                return ResourceManager.GetString("AirRefund1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;RF;;189;2800020142;1A1073783;001001
        ///AMD 2800011312;1/1;    28MAR;LESU
        ///ST180072;1A1073783
        ///MUC1A          ;  01;IEVU22221;72320566;;;;;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;
        ///B-TRFP
        ///C-7906/ 5555LESU-        -I--0-I
        ///D-070328;070328;070328
        ///RFDL;01MAR07;I;UAH6278.00;3450.00;2828.00;;;;;;XT397.10;3225.10;
        ///KRF ;QUAH213.60   YQ   ;QUAH78.10    CH   ;QUAH47.00    FR   ;QUAH58.40    FR   ;;;;;;;;;;;;;;;;;;;;;;;;;;
        ///I-001;01SVYATASH/DMYTRO MR;;;;
        ///T-E074-6972205888
        ///R-074-6972205888;28MAR07
        ///SAC074 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirRefund2 {
            get {
                return ResourceManager.GetString("AirRefund2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;RF;;190;2000028077;1A1131927;001001
        ///AMD 2000005200;1/1;    20FEB;AASU
        ///GW3671314;1A1131927
        ///MUC1A          ;  01;IEVU22118;72320135;;;;;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;
        ///B-TRFP
        ///C-7906/ 0005AASU-        -M--0-I
        ///D-070220;070220;070220
        ///RFDL;20NOV06;I;UAH2323.00;2323.00;;;;;;;;;
        ///I-001;01ZOLOTUKHIN/ANDRIY MR;;;;
        ///T-A566-4314439940
        ///R-566-4314439940;20FEB07
        ///FM1.00P/0.00A
        ///FPCASH
        ///FTGR1406/06
        ///ENDX.
        /// </summary>
        internal static string AirRefund3 {
            get {
                return ResourceManager.GetString("AirRefund3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;RF;;190;2300021319;1A1326991;001001
        ///AMD 2300088630;1/1;    23FEB;LTSU
        ///GW3712330;1A1326991
        ///MUC1A          ;  01;ODSU23298;72321793;;;;;ODSU23298;72321793;;;;;;;;;;;;;;;;;;;;;;
        ///B-TRFP
        ///C-7906/ 0007LTSU-0007LTSU----
        ///D-090223;090223;090223
        ///KRF ;QUAH118.30   HF   ;QUAH3.90     UD   ;QUAH19.00    YK   ;QUAH11.40    UA   ;;;;;;;;;;;;;;;;;;;;;;;;;;
        ///I-001;01DIVYEYEV/OLEKSANDR MR;;;;
        ///T-E181-3324517394
        ///SAC
        ///FM1.00P
        ///FPCASH/UAH709.60
        ///ENDX.
        /// </summary>
        internal static string AirRefund4 {
            get {
                return ResourceManager.GetString("AirRefund4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;RF;;189;2800020142;1A1073783;001001
        ///AMD 2800011312;1/1;    28MAR;LESU
        ///ST180072;1A1073783
        ///MUC1A          ;  01;IEVU22221;72320566;;;;;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;
        ///B-TRFP
        ///C-7906/ 5555LESU-        -I--0-I
        ///D-070328;070328;070328
        ///RFDL;01MAR07;I;UAH6278.00;3450.00;2828.00;;;;;;XT397.10;3225.10;
        ///KRF ;QUAH213.60   YQ   ;QUAH78.10    CH   ;QUAH47.00    FR   ;QUAH58.40    FR   ;;;;;;;;;;;;;;;;;;;;;;;;;;
        ///I-001;01SVYATASH/DMYTRO MR;;;;
        ///T-E074-6972205888
        ///R-074-6972205888;28MAR07
        ///SAC074 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirRefund5 {
            get {
                return ResourceManager.GetString("AirRefund5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;RF;;190;0600027276;1A1326991;001001
        ///AMD 0601594264;1/1;    07JUN;YPSU
        ///GW3672915;1A1326991
        ///MUC1A          ;  01;DNKUW2100;72320662;;;;;DNKUW2100;72320662;;;;;;;;;;;;;;;;;;;;;;
        ///B-TRFP
        ///C-7906/ 3010YPSU-3010YPSU-I---
        ///D-110606;110606;110606
        ///RFDM;26MAY11;D;UAH3912;1996;1916;;;978;;;XT536;1474;29MAY11
        ///KRF ;QUAH393      HF   ;QUAH4        UD   ;QUAH96       YQ   ;QUAH28       YK   ;QUAH15       UA   ;;;;;;;;;;;;;;;;;;;;;;;;;
        ///I-001;01KOPTIEV/OLEKSANDR MR;;;;
        ///T-E181-2834313963
        ///TBS1-0200
        ///R-181-2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirRefund6 {
            get {
                return ResourceManager.GetString("AirRefund6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;IM;;247;1400020475;1A1326991;001001
        ///AMD 1400870477;1/1;              
        ///GW3671464;1A1326991;IEV1A0985;IMR
        ///MUC1A YCWIAP010;0101;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;VV YCWIAP
        ///B-BT
        ///C-7906/ 0101SNSU-1701GTSU----
        ///D-100608;100614;100614
        ///G-X  ;;IEVMOW;E1
        ///U-002X;002OKBP;KIEV BORYSPIL    ;SVO;MOSCOW SVO       ;VV    0451 Q Q 17JUN2140 0020 18JUN;HK01;HK01;L ;0;733;;;;B ;;ET;0140 ;N;;473;;UA;RU;C 
        ///I-001;01BLOKHA/OKSANA MRS;;APIEV 380 44 20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirReservation1 {
            get {
                return ResourceManager.GetString("AirReservation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;IM;;247;2300021138;1A1326991;001001
        ///AMD 2300889776;1/1;              
        ///GW3671468;1A1326991;IEV1A0985;IMR
        ///MUC1A 34N4TF027;1212;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;7W HQNMK 
        ///B-BT
        ///C-7906/ 2602OISU-2602OISU----
        ///D-100617;100623;100623
        ///G-X  ;;IEVIEV;E1
        ///U-001X;013OKBP;KIEV BORYSPIL    ;KGD;KHRABROVO APT    ;7W    0705 G G 19JUL0800 0950 19JUL;HK12;HK12;M ;0;E95;;;;B ;;ET;0150 ;N;;530;;UA;RU;  
        ///U-002X;014OKGD;KHRABROVO APT    ;KBP;KIEV  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirReservation2 {
            get {
                return ResourceManager.GetString("AirReservation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;IM;;247;2300016439;1A1326991;001001
        ///AMD 2300889235;1/1;              
        ///GW3671468;1A1326991;IEV1A0985;IMR
        ///MUC1A X77NV9007;0101;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;Z6 QNZ75 
        ///B-BT/RT
        ///C-7906/ 2710YDSU-2602OISU----
        ///D-100623;100623;100623
        ///G-   ;;IEVIEV;
        ///U-003X;002OKBP;KIEV BORYSPIL    ;SIP;SIMFEROPOL       ;Z6    0023 Q Q 28JUN1415 1540 28JUN;HK01;HK01;L ;0;735;;;;A ;;ET;0125 ;N;;398;;UA;UA;  
        ///U-004X;003OSIP;SIMFEROPOL       ;KBP;KIEV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirReservation3 {
            get {
                return ResourceManager.GetString("AirReservation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;IM;;247;1900013474;1A1326991;001001
        ///AMD 1900882511;1/1;              
        ///GW3671468;1A1326991;IEV1A0985;IMR
        ///MUC1A 4K97UB012;0101;SIPUW2100;72321266;SIPUW2100;72321266;SIPUW2100;72321266;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;VV 4K97UB
        ///B-BT
        ///C-7906/ 1010DNSU-2602OISU----
        ///D-100618;100619;100619
        ///G-X  ;;SIPMOW;E1
        ///U-001X;002OSIP;SIMFEROPOL       ;SVO;MOSCOW SVO       ;VV    0615 D D 22JUN0710 1020 22JUN;HK01;HK01;L ;0;735;;;;;;ET;0210 ;N;;773;;UA;RU;C 
        ///I-001;01SEREBRYAKOV/ALEKSEY MR;;APSIP 0652-5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirReservation4 {
            get {
                return ResourceManager.GetString("AirReservation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;IM;;247;0200032788;1A1326991;001001
        ///AMD 0201023849;1/1;              
        ///GW3671543;1A1326991;IEV1A0985;IMR
        ///MUC1A 3EF5KM014;0202;KWGUW2100;72321270;KWGUW2100;72321270;KWGUW2100;72321270;KWGUW2100;72321270;;;;;;;;;;;;;;;;;;;;;;HY NSWED 
        ///B-BT
        ///C-7906/ 8888GSSU-8888GSSU----
        ///D-100821;100902;100902
        ///G-X  ;;IEVIEV;
        ///U-001X;003OKBP;KIEV BORYSPIL    ;TAS;TASHKENT         ;HY    0742 Y Y 12OCT2050 0305 13OCT;RR02;RR02;D ;0;763;;;;A ;;ET;0415 ;N;;1935;;UA;UZ;  
        ///U-002X;004OTAS;TASHKENT         ;KUL;KUALA  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirReservation5 {
            get {
                return ResourceManager.GetString("AirReservation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;IM;;239;0300004530;1A1326991;001001
        ///AMD 0301139478;1/1;              
        ///GW3670692;1A1326991;IEV1A0985;IMR
        ///MUC1A X4G7QN020;1201;QLHLH0564;;IEVLH0100;72390146;IEVLH0100;72390146;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;LH X4G7QN
        ///B-BT/P1
        ///C-7906/ 1000APRC-1111SASU----
        ///D-101029;101103;101103
        ///G-X  ;;IEVIEV;E1
        ///U-002X;013OKBP;KIEV BORYSPIL    ;DUS;DUESSELDORF      ;LH    3005 W W 21NOV1520 1710 21NOV;HK01;HK01;S ;0;CR7;;;;B ;1435 ;ET;0250 ;N;;1055;;UA;DE;  
        ///Y-002;013KBP;KIEV BORYSPIL;DUS;DUESSELDOR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirReservation6 {
            get {
                return ResourceManager.GetString("AirReservation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;IM;;247;0200019989;1A1326991;001001
        ///AMD 0201583554;1/1;              
        ///GW3671462;1A1326991;IEV1A0985;IMR
        ///MUC1A 2P3MAO015;0501;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;PS RDE26 
        ///B-BT/P4
        ///C-7906/ 1804AASU-0029ARSU----
        ///D-110602;110602;110602
        ///G-X  ;;IEVIEV;
        ///U-001X;006OKBP;KIEV BORYSPIL    ;TLV;TEL AVIV B GURION;PS    0775 K K 04JUL0955 1255 04JUL;HK01;HK01;B ;0;735;;;;F ;;ET;0300 ;N;;1284;;UA;IL;3 
        ///U-002X;007OTLV;TEL AVIV B GURION;KBP;KIE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirReservation7 {
            get {
                return ResourceManager.GetString("AirReservation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;2600031736;GW3670495;001001
        ///AMD 2600018245;1/1;              
        ///GW3670922;GW3670495;IEVU23561;AIR
        ///MUC1A 2JSYHH009;0101;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;VV 2JSYHH
        ///A-AEROSVIT AIRLINES;VV 8702
        ///B-TTP/T1
        ///C-7906/ 1984LXSU-1962VZSU-I-0--
        ///D-090325;090326;090326
        ///G-X  ;;IEVIEV;
        ///H-003;002OKBP;KIEV BORISPOL    ;JFK;NEW YORK JFK     ;VV    0131 V V 24APR1300 1625 24APR;OK01;HK01;L ;0;763;;;PC ;B ;;ET;1025 ;N;4693;UA;US;4 
        ///H-004;00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket1 {
            get {
                return ResourceManager.GetString("AirTicket1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;246;0800017689;1A1326991;001001
        ///AMD 0800201212;1/1;              
        ///ST183556;1A1326991;IEV1A0985;AIR
        ///MUC1A YYHRMO038;0101;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;TK RQHXCD
        ///A-TURKISH AIRLINES;TK 2354
        ///B-TTP/ET
        ///C-7906/ 1121IGSU-1121IGSU-I-0--
        ///D-090507;090508;090508
        ///G-X  ;;DOKDOK;E1
        ///H-005;002ODOK;DONETSK          ;IST;ISTANBUL         ;TK    1452 H H 15MAY1215 1420 15MAY;OK01;HK01;M ;0;738;;;30K;;;ET;0205 ;N;660;UA;TR;I 
        ///H-002;003XI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket10 {
            get {
                return ResourceManager.GetString("AirTicket10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;232;2500010439;1A1073783;001001
        ///AMD 2500015046;1/3;              
        ///ST182173;1A1073783
        ///MUC1A 2RDWEY019;0301;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;PS RF2L5 
        ///A-UKRAINE INTL AIRLINES;PS 5666
        ///B-TTP
        ///C-7906/ 1112SHSU-1112SHSU-I-0--
        ///D-070623;070625;070625
        ///G-X  ;;IEVIEV;E1
        ///H-003;004OKBP;KIEV BORISPOL    ;MAD;MADRID BARAJAS   ;PS    0941 Y Y 26JUN0755 1120 26JUN;OK01;HK01;B ;0;737;;;20K;B ;;ET;0425 ;N;1791
        ///H-002;005OMAD;MADRID BARAJAS  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket11 {
            get {
                return ResourceManager.GetString("AirTicket11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;232;2300011637;1A1073783;001001
        ///AMD 2300016534;1/1;              
        ///ST182176;1A1073783
        ///MUC1A YM4RLY020;0404;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;VV NRLJP 
        ///A-AEROSVIT AIRLINES;VV 8702
        ///B-TTP
        ///C-7906/ 1111AASU-1111AASU-F-N--
        ///D-070717;070723;070723
        ///G-X  ;;IEVIEV;E1
        ///H-003;005OKBP;KIEV BORISPOL    ;BUD;BUDAPEST         ;VV    4111 C D 27JUL1610 1655 27JUL;OK04;HK04;L ;0;734;;;30K;;;;0145 ;N;567
        ///H-004;006OBUD;BUDAPEST         ;KBP;KI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket12 {
            get {
                return ResourceManager.GetString("AirTicket12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;242;2300028382;1A1073783;001001
        ///AMD 2300023530;1/2;              
        ///ST183551;1A1073783
        ///MUC1A X4WORA027;0301;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;BA NOSYNC;PS RBSQY 
        ///A-BRITISH AIRWAYS;BA 1256
        ///B-TTP/ET/S4-6,8
        ///C-7906/ 3072SGSU-5505YKSU-I-5--
        ///D-071112;071123;071123
        ///G-X  ;;IEVIEV;
        ///H-016;004OKBP;KIEV BORISPOL    ;LHR;LONDON LHR       ;BA    0883 J J 02JAN1415 1550 02JAN;OK01;HK01;M ;0;320;;;PC ;B ;;ET;0335 ;N;1370;UA;GB
        ///H-000;000OL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket13 {
            get {
                return ResourceManager.GetString("AirTicket13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;252;0800026579;1A1073783;001001
        ///AMD 0800025706;1/1;              
        ///ST183551;1A1073783
        ///MUC1A ZXDGRV038;0101;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;BA NOSYNC;EK ERW5KW;OS HN1ZX 
        ///A-UKRAINE INTL AIRLINES;PS 5666
        ///B-TTP/S4-6/PT
        ///C-7906/ 3072SGSU-5505YKSU-I-0--
        ///D-071116;080108;080108
        ///G-X  ;;LONVIE;
        ///H-001;004OLHR;LONDON LHR       ;DXB;DUBAI            ;EK    0006 F F 19FEB2200 0845 20FEB;OK01;HK01;M ;0;773;;;40K;3 ;;ET;0645 ;N;3427;GB;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket14 {
            get {
                return ResourceManager.GetString("AirTicket14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;232;0900018095;1A1073783;001001
        ///AMD 0900042998;1/1;              
        ///ST182175;1A1073783
        ///MUC1A 45KB3P014;0101;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;VV 45KB3P
        ///A-AEROSVIT AIRLINES;VV 8702
        ///B-TTP/ET
        ///C-7906/ 1304AYSU-1304AYSU-I-0--
        ///D-081009;081009;081009
        ///G-X  ;;IEVIEV;E1
        ///H-001;002OKBP;KIEV BORISPOL    ;SVO;MOSCOW SVO       ;VV    0407 C C 10OCT1310 1545 10OCT;OK01;HK01;L ;0;734;;;30K;B ;;ET;0135 ;N;473;UA;RU;C 
        ///H-002;003OSVO;MOSCOW S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket15 {
            get {
                return ResourceManager.GetString("AirTicket15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;232;0600043254;1A1073783;001001
        ///AMD 0600050795;1/1;              
        ///ST182171;1A1073783
        ///MUC1A 3Q3VDU015;0303;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;IEVU22221;72320566;;;;;;;;;;;;;;;;;;;;;;LH 3Q3VDU
        ///A-LUFTHANSA;LH 2203
        ///B-TTP
        ///C-7906/ 2222SASU-3072SGSU-F-N--
        ///D-090306;090306;090306
        ///G-X  ;;IEVIEV;E1
        ///H-003;004OKBP;KIEV BORISPOL    ;FRA;FRANKFURT        ;LH    3237 H H 10MAR1405 1550 10MAR;OK03;HK03;S ;0;321;;;20K;B ;1320 ;ET;0245 ;N;988;UA;DE;1 
        ///H-004;005OFRA;FRANKFURT      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket16 {
            get {
                return ResourceManager.GetString("AirTicket16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;2200055034;1A1326991;001001
        ///AMD 2200715934;1/1;              
        ///GW3711580;1A1326991;IEV1A0985;AIR
        ///MUC1A 5NDLBF019;0202;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23401;72321874;;;;;;;;;;;;;;;;;;;;;;LO H0GH6 
        ///A-LOT POLISH AIRLINES;LO 0803
        ///B-TTP/RT
        ///C-7906/ 1984LXSU-1812NASU-I-0--
        ///D-100319;100322;100322
        ///G-X  ;;IEVIEV;
        ///H-001;003OKBP;KIEV BORISPOL    ;WAW;WARSAW           ;LO    0752 Z Z 25MAR1445 1520 25MAR;OK02;HK02;M ;0;735;;;2PC;B ;;ET;0135 ;N;449;UA;PL;I 
        ///H-002;0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket17 {
            get {
                return ResourceManager.GetString("AirTicket17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;2700057671;1A1326991;001001
        ///AMD 2700836326;1/1;              
        ///GW3672602;1A1326991;IEV1A0985;AIR
        ///MUC1A YFR7OP020;0201;LWOUW2101;72320544;LWOUW2101;72320544;LWOUW2101;72320544;LWOUW2101;72320544;;;;;;;;;;;;;;;;;;;;;;TK R68U2C
        ///A-TURKISH AIRLINES;TK 2354
        ///B-TTP/P1
        ///C-7906/ 2204NGSU-2204NGSU-I-0--
        ///D-100524;100527;100527
        ///G-X  ;;LWOLWO;
        ///H-006;003OLWO;LVIV SNILOW      ;IST;ISTANBUL         ;TK    0442 T T 07JUN1530 1735 07JUN;OK01;HK01;M ;0;319;;;30K;;;ET;0205 ;N;655;UA;TR;  
        ///H-005;004OIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket18 {
            get {
                return ResourceManager.GetString("AirTicket18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;223;2000015820;1A1326991;001001
        ///AMD 2001002280;1/1;              
        ///GW3673416;1A1326991;IEV1A0985;AIR
        ///MUC1A 23PZ9H005;0202;IEVU228DP;;IEVU228DP;;IEVU228DP;;SIPUW2100;72321266;;;;;;;;;;;;;;;;;;;;;;VV 23PZ9H
        ///A-AEROSVIT AIRLINES;VV 8702
        ///B-TTP
        ///C-7906/ 0001AASU-2805SASU-I-0--
        ///D-100820;100820;100820
        ///G-X  ;;UKSMOW;E1
        ///H-001;003OUKS;SEVASTOPOL BELBEK;KBP;KIEV BORYSPIL    ;VV    4088 U U 30AUG1910 2035 30AUG;OK02;HK02;N ;0;ER4;;;20K;;;ET;0125 ; ;410;UA;UA;A 
        ///X-001;003OUKS;SEVASTOPOL BELBEK;KBP; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket19 {
            get {
                return ResourceManager.GetString("AirTicket19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;239;0100027955;1A1326991;001001
        ///AMD 0100128563;1/1;              
        ///GW3671292;1A1326991;IEV1A0985;AIR
        ///MUC1A ZYT5D9034;1005;QLHLH0564;;IEVLH0102;72390975;IEVLH0102;72390975;DOKC32530;72320942;;;;;;;;;;;;;;;;;;;;;;LH ZYT5D9
        ///A-LUFTHANSA;LH 2203
        ///B-TTP/P1-5
        ///C-7906/ 1000APRC-0001AASU-M-9--
        ///D-090323;090401;090401
        ///G-X  ;;DOKDOK;E1
        ///H-004;011ODOK;DONETSK          ;MUC;MUNICH           ;LH    3249 W W 14APR1600 1805 14APR;OK05;HK05;M ;0;735;;;20K;;;ET;0305 ;N;1193;UA;DE;2 
        ///H-003;012XMUC;MUNICH   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket2 {
            get {
                return ResourceManager.GetString("AirTicket2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;257;1900033736;1A1326991;001001
        ///AMD 1901000738;1/1;              
        ///GW3671466;1A1326991;IEV1A0985;AIR
        ///MUC1A 2OCWYX016;0101;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;TK SIHRHI;VV 2OCWYX
        ///A-AEROSVIT AIRLINES;VV 8702
        ///B-TTP/ET/RT/S2
        ///C-7906/ 0101SNSU-0101SNSU-M-E--
        ///D-100819;100819;100819
        ///G-X  ;;IEVBKK;
        ///H-011;002OKBP;KIEV BORYSPIL    ;BKK;BKK SUVARNABHUMI ;VV    0171 M M 20AUG1400 0330 21AUG;OK01;HK01;L ;0;763;;;20K;B ;;ET;0930 ;N;4592;UA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket20 {
            get {
                return ResourceManager.GetString("AirTicket20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;IM;;247;2400016664;1A1326991;001001
        ///AMD 2401065459;1/1;              
        ///GW3673003;1A1326991;IEV1A0985;IMR
        ///MUC1A 36AJYC032;0301;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;IEVUW2100;72320220;;;;;;;;;;;;;;;;;;;;;;VV 36AJYC
        ///B-BT/P3/RT
        ///C-7906/ 1804AASU-1804AASU----
        ///D-100909;100924;100924
        ///G-X  ;;IEVIEV;E1
        ///U-010X;004OKBP;KIEV BORYSPIL    ;RIX;RIGA AIRPORT     ;VV    0295 X X 14NOV2215 2400 15NOV;HK01;HK01;L ;0;ER4;;;;B ;;ET;0145 ;N;;537;;UA;LV;  
        ///U-006X;005ORIX;RIGA AIRPORT     ;KBP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket21 {
            get {
                return ResourceManager.GetString("AirTicket21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;257;0400057189;1A1326991;001001
        ///AMD 0401315868;1/1;              
        ///GW3711579;1A1326991;IEV1A0985;AIR
        ///MUC1A YIHXKB011;0101;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23401;72321874;;;;;;;;;;;;;;;;;;;;;;TK RGF8A8;VV YIHXKB
        ///A-AEROSVIT AIRLINES;VV 8702
        ///B-TTP/RT/T1
        ///C-7906/ 2004TASU-1982LUSU-I-0--
        ///D-110204;110204;110204
        ///G-X  ;;IEVIST;E1
        ///H-003;002OKBP;KIEV BORYSPIL    ;IST;ISTANBUL         ;VV    0261 T T 08FEB0700 0910 08FEB;OK01;HK01;L ;0;A81;;;20K;B ;;ET;0210 ;N;656;UA;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket22 {
            get {
                return ResourceManager.GetString("AirTicket22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;2800016405;1A1326991;001001
        ///AMD 2801300815;1/1;              
        ///GW3711579;1A1326991;IEV1A0985;AIR
        ///MUC1A 7DYPWN005;0101;IEVU23401;72321874;IEVU23401;72321874;IEVU23401;72321874;IEVU23401;72321874;;;;;;;;;;;;;;;;;;;;;;PS RPWLX 
        ///A-UKRAINE INTL AIRLINES;PS 5666
        ///B-TTP/RT
        ///C-7906/ 1982LUSU-1982LUSU-I-0--
        ///D-110128;110128;110128
        ///G-X  ;;IEVIEV;E1
        ///H-001;002OKBP;KIEV BORYSPIL    ;BRU;BRUSSELS         ;PS    0901 K K 31JAN1645 1845 31JAN;OK01;HK01;S ;0;735;;;20K;F ;;ET;0300 ;N;1157;UA;BE;M 
        ///H- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket23 {
            get {
                return ResourceManager.GetString("AirTicket23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;1100010838;1A1326991;001001
        ///AMD 1101384466;1/1;              
        ///GW3670922;1A1326991;IEV1A0985;AIR
        ///MUC1A 2FLC7O004;0101;IEVU23401;72321874;IEVU23401;72321874;IEVU23401;72321874;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;SU EZBKEZ
        ///A-AEROFLOT;SU 5552
        ///B-TTP
        ///C-7906/ 7337EVSU-1979SHSU-I-0--
        ///D-110311;110311;110311
        ///G-X  ;;IEVIEV;
        ///H-001;002OKBP;KIEV BORYSPIL    ;SVO;MOSCOW SVO       ;SU    0184 V V 14MAR1430 1700 14MAR;OK01;HK01;L ;0;321;;;20K;B ;;ET;0130 ;N;473;UA;RU;F 
        ///H-002;003XSVO;MOSCOW  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket24 {
            get {
                return ResourceManager.GetString("AirTicket24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;1200008108;1A1326991;001001
        ///AMD 1201388310;1/1;              
        ///GW3670923;1A1326991;IEV1A0985;AIR
        ///MUC1A 2TYGC9011;0202;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;LH 2TYGC9
        ///A-LUFTHANSA;LH 2203
        ///B-TTP
        ///C-7906/ 9999OPSU-9999OPSU-I-0--
        ///D-110312;110312;110312
        ///G-X  ;;IEVIEV;E1
        ///H-003;003OKBP;KIEV BORYSPIL    ;FRA;FRANKFURT        ;LH    1493 L L 23APR0535 0725 23APR;OK02;HK02;S ;0;321;;;20K;F ;0450 ;ET;0250 ;N;988;UA;DE;1 
        ///H-004;004XFRA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket25 {
            get {
                return ResourceManager.GetString("AirTicket25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;287;0200012565;1A1326991;001001
        ///AMD 0201365607;1/1;              
        ///GW3711580;1A1326991;IEV1A0985;AIR
        ///MUC1A 72LWN7035;0101;IEVU23401;72321874;IEVU23401;72321874;IEVU23401;72321874;IEVU23401;72321874;;;;;;;;;;;;;;;;;;;;;;AF 72LWN7;DL GAIQJL;KL 72LWN7;PS RL79Z ;US BJTPE7
        ///A-US AIRWAYS;US 0372
        ///B-TTP/T2/RT
        ///C-7906/ 1982LUSU-1812NASU-I-0--
        ///D-110301;110302;110302
        ///G-   ;;ORLPHL;US
        ///H-006;005OMCO;ORLANDO INT      ;PHL;PHILADELPHIA INTL;US    0554 L L 10MAR1020 1241 10MAR;OK01;HK01;;0;320;;;0PC;;; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket26 {
            get {
                return ResourceManager.GetString("AirTicket26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;277;1000096505;1A1326991;001001
        ///AMD 1008826135;1/1;              
        ///GW3670495;1A1326991;IEV1A0985;AIR
        ///MUC1A 7VEMFV016;0101;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;B2 SEAUGA;PS RZRRR ;S7 SZKW2 ;UT 1LL02F
        ///A-BELAVIA;B2 6285
        ///B-TTP/T1/RT
        ///C-7906/ 9999OPSU-9999OPSU-I-0--
        ///D-160610;160610;160610
        ///G-X  ;;IEVROV;E1
        ///H-007;002OIEV;KIEV ZHULIANY INT;MSQ;MINSK MINSK 2 INT;B2    0848 U U 12JUN0615 0710 12JUN;OK01;HK01;N ;0;733;;;20K;A ;;ET;0055 ; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket27 {
            get {
                return ResourceManager.GetString("AirTicket27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;252;0000000000;1A1326991;001001
        ///AMD 1508847637;1/1;              
        ///GW3670495;1A1326991;IEV1A0985;AIR
        ///MUC1A 74WTWN009;0101;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;AF 74WTWN;KL 74WTWN
        ///A-AIR FRANCE;AF 0571
        ///B-TTP
        ///C-7906/ 9999OPSU-1701INSU-I-0--
        ///D-160614;160615;160615
        ///G-X  ;;IEVIEV;E1
        ///H-001;002OKBP;KIEV BORYSPIL    ;CDG;PARIS CDG        ;AF    1653 X X 03JUL20160700 0920 03JUL2016;OK01;HK01;BS;0;319;;;1PC;;0620 ;ET;0320 ;N;1268;UA;FR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket28 {
            get {
                return ResourceManager.GetString("AirTicket28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;241;0000000000;1A1326991;001001
        ///AMD 1708858222;1/1;              
        ///GW3670495;1A1326991;IEV1A0985;AIR
        ///MUC1A 77JCA6009;0202;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;PS S1393
        ///A-UKRAINE INTL AIRLINES;PS 5666
        ///B-TTP/RT
        ///C-7906/ 2000ZXSU-9999OPSU-I-0--
        ///D-160615;160617;160617
        ///G-X  ;;ODSODS;
        ///H-001;003OODS;ODESA            ;TLV;TEL AVIV B GURION;PS    0787 L L 21JUL2130 0015 22JUL;OK02;HK02;N ;0;738;;;0PC;;;ET;0245 ;N;1027;UA;IL;3 
        ///H-002;0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket29 {
            get {
                return ResourceManager.GetString("AirTicket29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;0100008712;1A1326991;001001
        ///AMD 0100127720;1/1;              
        ///GW3670922;1A1326991;IEV1A0985;AIR
        ///MUC1A 39CGHB024;0202;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;KL ZK2M5D
        ///A-KLM ROYAL DUTCH AIRLINES;KL 0744
        ///B-TTP/RT/ET/T1
        ///C-7906/ 1984LXSU-1984LXSU-I-0--
        ///D-090401;090401;090401
        ///G-X  ;;IEVIEV;
        ///H-028;003OKBP;KIEV BORISPOL    ;AMS;AMSTERDAM        ;KL    1386 Q Q 07APR1730 1935 07APR;OK02;HK02;M ;0;73W;;;PC ;B ;;ET;0305 ; ;1129;UA;NL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket3 {
            get {
                return ResourceManager.GetString("AirTicket3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;241;0000000000;1A1326991;001001
        ///AMD 1608854636;1/1;              
        ///GW3673250;1A1326991;IEV1A0985;AIR
        ///MUC1A 78VQOD011;0101;ODSUW2100;72321244;ODSUW2100;72321244;ODSUW2100;72321244;ODSUW2100;72321244;;;;;;;;;;;;;;;;;;;;;;PS S1M71
        ///A-UKRAINE INTL AIRLINES;PS 5666
        ///B-TTP/RT
        ///C-7906/ 1965MGSU-1965MGSU-F-N--
        ///D-160616;160616;160616
        ///G-X  ;;ODSODS;E1
        ///H-001;002OODS;ODESA            ;IST;ISTANBUL         ;PS    0717 L L 17JUN20161145 1315 17JUN2016;OK01;HK01;N ;0;735;;;2PC;;;ET;0130 ;N;392;UA;TR;I  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket30 {
            get {
                return ResourceManager.GetString("AirTicket30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;257;3100025773;1A1326991;001001
        ///AMD 3100126925;1/1;              
        ///GW3671291;1A1326991;IEV1A0985;AIR
        ///MUC1A 32IU3O010;0101;DOKC32530;72320942;DOKC32530;72320942;DOKC32530;72320942;DOKC32530;72320942;;;;;;;;;;;;;;;;;;;;;;LH 32IU3O;OS 32IU3O
        ///A-AUSTRIAN;OS 2575
        ///B-TTP/T2
        ///C-7906/ 0001AASU-0001AASU-I-0--
        ///D-090331;090331;090331
        ///G-X  ;;BLQBLQ;EU
        ///H-003;004OBLQ;BOLOGNA          ;VIE;VIENNA SCHWECHAT ;OS    0548 K K 10APR1105 1250 10APR;OK01;HK01;S ;0;DH3;;TYROLEAN AIRWAYS;20K;;1025 ;ET;0145 ;N;3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket4 {
            get {
                return ResourceManager.GetString("AirTicket4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;233;1800020197;GW3670821;001001
        ///AMD 1800013663;1/2;              
        ///GW3671292;GW3670821
        ///MUC1A YN7OXG015;0201;DOKC32530;72320942;DOKC32530;72320942;DOKC32530;72320942;DOKC32530;72320942;;;;;;;;;;;;;;;;;;;;;;LH YN7OXG
        ///A-LUFTHANSA;LH 2203
        ///B-TTP
        ///C-7906/ 7777SVSU-0001AASU-B-N--
        ///D-090318;090318;090318
        ///G-X  ;;DOKDOK;E1
        ///H-001;003ODOK;DONETSK          ;MUC;MUNICH           ;LH    3249 U U 20APR1600 1805 20APR;OK01;HK01;M ;0;CR9;;LUFTHANSA CITYLINE;20K;;;ET;0305 ;N;1193;UA;DE;2 
        ///H-002;004XMUC;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket5 {
            get {
                return ResourceManager.GetString("AirTicket5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;267;2600049423;1A1131927;001001
        ///AMD 2600027918;1/1;              
        ///GW3671313;1A1131927;IEVU22118;AIR
        ///MUC1A X43J2U048;0202;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;AF 26G4BT;KL CLRFEU;PS RF703 
        ///A-AIR FRANCE;AF 0571
        ///B-TTP
        ///C-7906/ 0007OPSU-0007OPSU-I-0--
        ///D-081229;090326;090326
        ///G-X  ;;IEVIEV;
        ///H-008;003OKBP;KIEV BORISPOL    ;CDG;PARIS CDG        ;PS    0701 D D 01MAY0630 0910 01MAY;OK02;HK02;B ;0;733;;;PC ;B ;;ET;0340 ;N;1268;UA;FR;2B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket6 {
            get {
                return ResourceManager.GetString("AirTicket6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;2600031736;GW3670495;001001
        ///AMD 2600018245;1/1;              
        ///GW3670922;GW3670495;IEVU23561;AIR
        ///MUC1A 2JSYHH009;0101;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;VV 2JSYHH
        ///A-AEROSVIT AIRLINES;VV 8702
        ///B-TTP/T1
        ///C-7906/ 1984LXSU-1962VZSU-I-0--
        ///D-090325;090326;090326
        ///G-X  ;;IEVIEV;
        ///H-003;002OKBP;KIEV BORISPOL    ;JFK;NEW YORK JFK     ;VV    0131 V V 24APR1300 1625 24APR;OK01;HK01;L ;0;763;;;PC ;B ;;ET;1025 ;N;4693;UA;US;4 
        ///H-004;00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket7 {
            get {
                return ResourceManager.GetString("AirTicket7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;2200006268;1A1326991;001001
        ///AMD 2200165399;1/1;              
        ///GW3670922;1A1326991;IEV1A0985;AIR
        ///MUC1A 5U2CGW058;0101;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;TK RSVVNR
        ///A-TURKISH AIRLINES;TK 2354
        ///B-TTP/P1/S4-5
        ///C-7906/ 7337EVSU-7337EVSU-M-1--
        ///D-081127;090422;090422
        ///G-X  ;;KRTIEV;
        ///H-013;004OKRT;KHARTOUM         ;IST;ISTANBUL         ;TK    1151 Y Y 23APR0220 0635 23APR;OK01;HK01;M ;0;738;;;20K;;;ET;0415 ;N;1761;SD;TR;I 
        ///H-014; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket8 {
            get {
                return ResourceManager.GetString("AirTicket8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;7A;;247;0300009658;1A1131927;001001
        ///AMD 0300025951;1/1;              
        ///GW3671316;1A1131927;IEVU22118;AIR
        ///MUC1A ZETE6I006;0101;ODSU22209;72320135;ODSU22209;72320135;ODSU22209;72320135;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;VV ZETE6I
        ///A-AEROSVIT AIRLINES;VV 8702
        ///B-TTP/S2/RT
        ///C-7906/ 0001AASU-0001AASU-B-N--
        ///D-081203;081203;081203
        ///G-   ;;ODSIEV;UA
        ///H-005;002OODS;ODESSA           ;KBP;KIEV BORISPOL    ;VV    0002 P P 04DEC0840 0950 04DEC;OK01;HK01;S ;0;YK2;;;20K;;;ET;0110 ;N;266;UA;UA;A 
        ///K-FUSD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AirTicket9 {
            get {
                return ResourceManager.GetString("AirTicket9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;MA;;233;2400022321;GW3670495;001001
        ///AMD 2400018172;1/1;VOID24MAR;LXSU
        ///GW3670922;GW3670495
        ///MUC1A ZNMNA5012;0101;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;IEVU23561;72320441;;;;;;;;;;;;;;;;;;;;;;VV ZNMNA5
        ///I-001;01ZINCHENKO/YURIYMR;;APIEV 38044-4902888 - ARIOLA GROUP LTD - A//568 47 85 ALEKSANDR;;
        ///T-K870-3324622080
        ///FPCASH
        ///ENDX.
        /// </summary>
        internal static string AirVoid1 {
            get {
                return ResourceManager.GetString("AirVoid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;MA;;190;0500022186;1A1131927;001001
        ///AMD 0500022493;1/1;VOID06AUG;AASU
        ///GW3671316;1A1131927
        ///MUC1A          ;0301;IEVU22118;72320135;;;;;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;
        ///I-001;01GLADKIKH/VASYLMR;;;;
        ///T- 870-3103872242
        ///R-870-3103872242;05AUG08
        ///FPCASH
        ///ENDX.
        /// </summary>
        internal static string AirVoid2 {
            get {
                return ResourceManager.GetString("AirVoid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;MA;;233;2200027890;1A1131927;001001
        ///AMD 2200016346;1/1;RSTD22FEB;ABSU
        ///GW3671316;1A1131927
        ///MUC1A 39YG5W013;0101;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;LH HRW5K 
        ///I-001;01KOSMATENKO/VITALIY MR;;AP4838600//-489-18-51/OOO ZHERMAN MOTORS!!!!!!!!!!!!;;
        ///T-K220-1791448244
        ///FPCASH
        ///ENDX.
        /// </summary>
        internal static string AirVoid3 {
            get {
                return ResourceManager.GetString("AirVoid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;MA;;233;1600018324;1A1131927;001001
        ///AMD 1600010030;1/1;RSTD17AUG;ADSU
        ///GW3671318;1A1131927
        ///MUC1A 3OLRUR017;0101;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;LH JWYKY 
        ///MCO067;006LH;2203;LUFTHANSA;IEV;TO-LUFTHANSA;AT-KIEV;16AUG;M;A;PENALTY FOR RBBK;**-;;F;UAH     505.00;N;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;UAH     505.00;;;-220-1777474363;;;;P1
        ///I-001;01MALICH/DARIA MRS;;APTEL.202-25-90;;
        ///TMCM220-1927917694;;L6
        ///MFM*C*0;L6
        ///MFPCASH;L6
        ///ENDX.
        /// </summary>
        internal static string AirVoid4 {
            get {
                return ResourceManager.GetString("AirVoid4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-BLK207;MA;;190;3000017090;1A1131927;001001
        ///AMD 3000006152;1/1;TRFX30MAR;AASU
        ///GW3671316;1A1131927
        ///MUC1A          ;0201;IEVU22118;72320135;;;;;IEVU22118;72320135;;;;;;;;;;;;;;;;;;;;;;
        ///I-001;01PUPYNINA/LARISA MRS;;;;
        ///T- 566-6972253583
        ///R-566-6972253583;30MAR07
        ///FPCASH
        ///ENDX.
        /// </summary>
        internal static string AirVoid5 {
            get {
                return ResourceManager.GetString("AirVoid5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бухгалтерия.
        /// </summary>
        internal static string CustomerReport_CustomerDepartmentName {
            get {
                return ResourceManager.GetString("CustomerReport_CustomerDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ІВЕКО УКРАЇНА ТОВ.
        /// </summary>
        internal static string CustomerReport_CustomerName {
            get {
                return ResourceManager.GetString("CustomerReport_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HK1/P/AZ/P3311054/AZ/28MAR70/M/02JUN18/MEHTIYEV/ELSHAN/H.
        /// </summary>
        internal static string GdsPassport1 {
            get {
                return ResourceManager.GetString("GdsPassport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата за авіадокумент № 870-3324622112
        ///за маршрутом KBP-JFK-KBP
        ///VLADIMIROV/VITALII MR.
        /// </summary>
        internal static string InvoiceItem_Text1 {
            get {
                return ResourceManager.GetString("InvoiceItem_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392008920256412JUL090910 PS566UKRAINE INTERNATIONAL AI09JUL09DAA5B2E2B807
        ///3L0B3L0B72321874 ZT7SG0         7Y5XINNYYAG02JUL0901012JUL09022
        ///UAH0000000534002UAH00000000  00000000  00000000  00000000  00000000  000000000000               
        ///NYNYN7NNNAYH NNNX   UA                             
        ///000000001000001000000000000001001000001000000000
        ///
        ///A02FEIRACHIOS/ALESSANDROMR          193625453109191898584301000004570      01  N
        ///
        ///A0402PS566UKRAINE INTE 311M HK12JUL1600 1755 2KBPKIEV/BORISPOLMXPMILAN/MALPENS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirMco1 {
            get {
                return ResourceManager.GetString("MirMco1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392012930560410JUL091203 Z6181DNIEPROAVIA JOINT STOCK 09JUL09DB139EDB13A1
        ///7Y5X7Y5X72320441 ZZZZZZ          Z7Y  NLXAG       000       001
        ///UAH0000000741002UAH00000000  00000000  00000000  00000000  00000000                             
        ///NNNYN5NNYAYR NNN    UA                             
        ///000000001000002000000001000001000000000000000000
        ///
        ///A02TYMCHENKO/MYKYTAMSTR             188464045109966495477001               01  N
        ///
        ///A0401Z6181DNIEPROAVIA  346N   09JUL0850      2KBPKIEV/BORISPOLIFOIVANO-FRANKOV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirRefund1 {
            get {
                return ResourceManager.GetString("MirRefund1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392011210220229MAY091559 PS566UKRAINE INTERNATIONAL AI02JUN09E997AAE2B807
        ///3L0B3L0B72321874 ZZZZZZ          Z3L  NINAG       000       001
        ///UAH0000000584002UAH00000000  00000000  00000000  00000000  00000000                             
        ///NNNYN5NNYAYR NNN    UA                             
        ///000000001000001000000001000001000000000000000000
        ///
        ///A02LUTSENKO/IGORMR                  148318836139578243699601               01  N
        ///
        ///A0401PS566UKRAINE INTE  67Q   02JUN2110      2SIPSIMFEROPOL   KBPKIEV/BORISPOL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirRefund2 {
            get {
                return ResourceManager.GetString("MirRefund2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392015360085911MAR131012 PS566UKRAINE INTERNATIONAL AI06MAR13FE854AFE2EF2
        ///5T795T7972321255 ZZZZZZ          Z5T  YDPAG       000       001
        ///UAH0000000013990UAH00000000  00000000  00000000  00000000  00000000                             
        ///NNNYN5NNYAYR NNN    UA                             
        ///000000001000002000000001000001000000000000000000
        ///
        ///A02TELENYK/SERGIYMR                 064305184143329771129101               01  N
        ///EN:TELENYK/SERGIYMR                                       
        ///
        ///A0401PS566UKRAINE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirRefundIssue1 {
            get {
                return ResourceManager.GetString("MirRefundIssue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392015261491813MAR130859 LH220LUFTHANSA               13MAR13E997ADFE2168
        ///3L0B3L0B72321874 ZZZZZZ          Z3L  NINAG       000       001
        ///UAH0000000059950UAH00000000  00000000  00000000  00000000  00000000                             
        ///NNNYN5NNYAYR NNNX   UA                             
        ///000000001000002000000001000001000000000000000000
        ///
        ///A02IAKOVENKO/VITALIIMR              071041517133321919488301               01  N
        ///
        ///A0401LH220LUFTHANSA   1493G   13MAR0555      2KBPKIEV/BORYSPILFRAFRANKFURT     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirRefundIssue2 {
            get {
                return ResourceManager.GetString("MirRefundIssue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392013540759911APR131254 PS566UKRAINE INTERNATIONAL AI23APR13B7E9F5FE2168
        ///373C373C72323495 ZZZZZZ         0784  N66AG       000       001
        ///UAH0000000054580UAH00000000  00000000  00000000  00000000  00000000                             
        ///NNNYN5NNYAYR NNNX   UA                             
        ///000000001000002000000001000001000000000000000000
        ///
        ///A02BALUIEV/ALEXANDRMR               100873988113390375965901               01  N
        ///
        ///A0401PS566UKRAINE INTE 802Z   23APR1110      2WAWWARSAW       KBPKIEV/BORYSPIL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirRefundIssue3 {
            get {
                return ResourceManager.GetString("MirRefundIssue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392018840023409APR131211 TK235TURKISH AIRLINES        21MAR13E7701DFE2168
        ///39J339J372324350 ZZZZZZ         0695  N65AG       000       001
        ///UAH0000000029100UAH00000000  00000000  00000000  00000000  00000000                             
        ///NNNYN5NNYAYR NNNX   UA                             
        ///000000001000004000000001000001000000000000000000
        ///
        ///A02SHEVCHENKO/GANNAMRS              073735134153390367507101               01  N
        ///EN:SHEVCHENKO/GANNAMRS                                    
        ///
        ///A0401TK235TURKISH  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirRefundIssue4 {
            get {
                return ResourceManager.GetString("MirRefundIssue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392014110553701JUL091536 S7421SIBERIA AIRLINES        03JUL09CADE35DB13A1
        ///7Y5X7Y5X72320441 VF88JE         7Y5XNNNNNAG01JUL0900001JUL09002
        ///UAH0000006878002UAH00000000  00000000  00000000  00000000  00000000  000000000500               
        ///NNNYN5NNYAYH NNNX   UA                             
        ///000000002000002000000001000001001000001000000000
        ///
        ///A02CHAIKOVSKA/ANZHELIKAMRS          182329616329966493324401000011214ADT   01  N
        ///A02MEZIN/ANDREYMR                   182329617359966493324501000011214ADT   01  N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket1 {
            get {
                return ResourceManager.GetString("MirTicket1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392018150166319MAR091235 PS566UKRAINE INTERNATIONAL AI21MAR09DAA5B2E2B807
        ///7Y5X3L0B72321874 M0X46G         7Y5XNVNYYAG19MAR0900019MAR09011
        ///UAH0000007346002UAH00000000  00000000  00000000  00000000  00000000  000001000000               
        ///NNNYN5NNYAYH NNNX   UA                             
        ///000000002002002000004001000001002000001000000000
        ///
        ///A02SUNDEN/GANNAMRS                  078739100039332339791401000003743ADT   01  N
        ///A02IATSENKO/VOLODYMYRMR             078739101069332339791501000003743ADT   01  N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket2 {
            get {
                return ResourceManager.GetString("MirTicket2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392013820442822FEB100912 VV870AEROSVIT AIRLINES       24FEB10E997ADE2B807
        ///3L0B3L0B72321874 KNPRGC         7Y5XSVNNAAG19FEB1000322FEB10027
        ///UAH0000001071002UAH00000000  00000000  00000000  00000000  00000000  000000000000               
        ///NNNYN7NNYAYA NNNX   UA                             
        ///000000001000001004000001000000002000004000000000
        ///
        ///A02BABAIEV/MYKOLAMR                            0          00         ADT   01  N
        ///
        ///A0405VV870AEROSVIT AIR 408V HK24FEB1700 1745 2SVOMOSCOW/SHEREMKBPKIEV/BORISPOL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket3 {
            get {
                return ResourceManager.GetString("MirTicket3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392011310443522FEB101220 SU555AEROFLOT RUSSIAN AIR    21MAR10E997AAE2B807
        ///3L0B3L0B72321874 WFD06G         7Y5XINNINAG22FEB1000022FEB10004
        ///UAH0000003603002UAH00000000  00000000  00000000  00000000  00000000  000000000500               
        ///NNNYN7NNYAYA NNNX   UA                             
        ///000000003000001000000001000000002000001000000000
        ///
        ///A02ISMAILOV/ELDARMR                            0          00         ADT   01  N
        ///A02ALKAYA/ZAFER                                0          00         ADT   01  N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket4 {
            get {
                return ResourceManager.GetString("MirTicket4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392011310443522FEB101220 SU555AEROFLOT RUSSIAN AIR    21MAR10E997AAE2B807
        ///3L0B3L0B72321874 WFD06G         7Y5XINNINAG22FEB1000022FEB10004
        ///UAH0000003603002UAH00000000  00000000  00000000  00000000  00000000  000000000500               
        ///NNNYN7NNYAYA NNNX   UA                             
        ///000000003000001000000001000000002000001000000000
        ///
        ///A02ISMAILOV/ELDARMR                            0          00         ADT   01  N
        ///A02ALKAYA/ZAFER                                0          00         ADT   01  N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket5 {
            get {
                return ResourceManager.GetString("MirTicket5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392011310443522FEB101220 SU555AEROFLOT RUSSIAN AIR    21MAR10E997AAE2B807
        ///3L0B3L0B72321874 WFD06G         7Y5XINNINAG22FEB1000022FEB10004
        ///UAH0000003603002UAH00000000  00000000  00000000  00000000  00000000  000000000500               
        ///NNNYN7NNYAYA NNNX   UA                             
        ///000000003000001000000001000000002000001000000000
        ///
        ///A02ISMAILOV/ELDARMR                            0          00         ADT   01  N
        ///A02ALKAYA/ZAFER                                0          00         ADT   01  N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket6 {
            get {
                return ResourceManager.GetString("MirTicket6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392011310443522FEB101220 SU555AEROFLOT RUSSIAN AIR    21MAR10E997AAE2B807
        ///3L0B3L0B72321874 WFD06G         7Y5XINNINAG22FEB1000022FEB10004
        ///UAH0000003603002UAH00000000  00000000  00000000  00000000  00000000  000000000500               
        ///NNNYN7NNYAYA NNNX   UA                             
        ///000000003000001000000001000000002000001000000000
        ///
        ///A02ISMAILOV/ELDARMR                            0          00         ADT   01  N
        ///A02ALKAYA/ZAFER                                0          00         ADT   01  N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket7 {
            get {
                return ResourceManager.GetString("MirTicket7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392013820442822FEB100912 VV870AEROSVIT AIRLINES       24FEB10E997ADE2B807
        ///3L0B3L0B72321874 KNPRGC         7Y5XSVNNAAG19FEB1000322FEB10027
        ///UAH0000001071002UAH00000000  00000000  00000000  00000000  00000000  000000000000               
        ///NNNYN7NNYAYA NNNX   UA                             
        ///000000001000001004000001000000002000004000000000
        ///
        ///A02BABAIEV/MYKOLAMR                            0          00         ADT   01  N
        ///
        ///A0405VV870AEROSVIT AIR 408V HK24FEB1700 1745 2SVOMOSCOW/SHEREMKBPKIEV/BORISPOL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket8 {
            get {
                return ResourceManager.GetString("MirTicket8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392021550131708APR100846ALH220DEUTSCHE LUFTHANSA AG   16APR10D9D76DADB08B
        ///7J8J7J8J99999992 ZG61X4          N3152N52AG07APR1000107APR10004
        ///UAH0000004914002UAH00000000  00000000  00000000  00000000  00000000  000000000000               
        ///NNNYN5NNYAYH NNNX   UA                             
        ///000000001000004000000001000001001000001000000000
        ///
        ///A02VASILEVSKAYA/NATALIAMRS          097710930050990104069501000006071ADT   01  N
        ///
        ///A0401LH220DEUTSCHE LUF3235V HK16APR 535A 715A2KBPKIEV/BORISPOLFRAFRANKFURT     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicket9 {
            get {
                return ResourceManager.GetString("MirTicket9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392036900716712MAR131412 PS566UKRAINE INTERNATIONAL AI11APR13E0902EFE2168
        ///62RZ373C72323495 TTS52O         62RZKSNNBAG21FEB1301912MAR13034
        ///UAH0000000203400UAH00000000  00000000  00000000  00000000  00000000  000000010000               
        ///NYNYN5NNYAYA NNNX   UA                             
        ///000001012000002000000001000001003000001000000000
        ///
        ///A01VOEVODYNO                        
        ///
        ///A02RAKOVA/ALINAMRS                             3390367904001         ADT   01  N
        ///SI:BEN:RAKOVA/ALINAMRS                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirTicketIssue1 {
            get {
                return ResourceManager.GetString("MirTicketIssue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392006690557707JUL091548 Z6181DNIEPROAVIA JOINT STOCK        DB139EDB13A1
        ///	7Y5X72320441 ZZZZZZ               NLXAG       000       001
        ///USD0000000000002UAH00000000  00000000  00000000  00000000  00000000                             
        ///NNNYN7NNYAYV NNN    UA                             
        ///000000001000000000000001000001000000000000000000
        ///
        ///A02COMERFORD/PHILLI                 188565784139966495478201               01  N
        ///
        ///A0701USD            UAH     1517.40               UAHT1:   23.00UAT2:    7.80UDT3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirVoid1 {
            get {
                return ResourceManager.GetString("MirVoid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T51G773392006690241121JUN091422 Z6181DNIEPROAVIA JOINT STOCK        E997AAE2B807
        ///	3L0B72321874 ZZZZZZ               NNAAG       000       001
        ///USD0000000000002UAH00000000  00000000  00000000  00000000  00000000                             
        ///NNNYN7NNYAYV NNN    UA                             
        ///000000001000000000000001000001000000000000000000
        ///
        ///A02PROKOPCHUK/DMYTR                 172839056119966492822901               01  N
        ///
        ///A0701USD            UAH      965.10               UAHT1:   23.00UAT2:    7.60UDT3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MirVoid2 {
            get {
                return ResourceManager.GetString("MirVoid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot;?&gt;
        ///&lt;Оплата&gt;
        ///	&lt;ИдСчета&gt;42a32a0affd5462284b39eadfbbfc5ec&lt;/ИдСчета&gt;
        ///	&lt;НомерСчета&gt;АБ-5477/1&lt;/НомерСчета&gt;
        ///	&lt;ДатаОплаты&gt;3/10/2011&lt;/ДатаОплаты&gt;
        ///	&lt;Сумма&gt;1056&lt;/Сумма&gt;
        ///	&lt;Валюта&gt;980&lt;/Валюта&gt;
        ///	&lt;СуммаУч&gt;1056&lt;/СуммаУч&gt;
        ///&lt;/Оплата&gt;.
        /// </summary>
        internal static string PaymentXml1 {
            get {
                return ResourceManager.GetString("PaymentXml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;EMD&lt;/TYPE&gt;&lt;CURRENCY&gt;РУБ&lt;/CURRENCY&gt;&lt;DEALDATE&gt;22062011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1710&lt;/DEALTIME&gt;&lt;OPTYPE&gt;SALE&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;REFUND&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;PENALTY&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;EMD6197945639&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;SHEBOLAEV/IGOR MR&lt;/FIO&gt;&lt;PASS&gt;ПС5001793820&lt;/PASS&gt;&lt;BIRTH_DATE&gt;01011948&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;421&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;421&lt;/TCC&gt;&lt;SALEDATE&gt;&lt;/SALEDATE&gt;&lt;SALETIME&gt;&lt;/SALETIME&gt;&lt;RETTYPE&gt;0&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaMco1 {
            get {
                return ResourceManager.GetString("SirenaMco1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;EMD&lt;/TYPE&gt;&lt;CURRENCY&gt;RUB&lt;/CURRENCY&gt;&lt;DEALDATE&gt;26062011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1523&lt;/DEALTIME&gt;&lt;OPTYPE&gt;SALE&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;REFUND&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;RECEIPT&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;EMD6197969915&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;FASSAKHOVA/GULYANISA MS&lt;/FIO&gt;&lt;PASS&gt;PS6510973654&lt;/PASS&gt;&lt;BIRTH_DATE&gt;13091965&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;362&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;362&lt;/TCC&gt;&lt;SALEDATE&gt;25062011&lt;/SALEDATE&gt;&lt;SALETIME&gt;1258&lt;/SA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaMco2 {
            get {
                return ResourceManager.GetString("SirenaMco2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;ETICKET&lt;/TYPE&gt;&lt;CURRENCY&gt;RUB&lt;/CURRENCY&gt;&lt;DEALDATE&gt;26062011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1523&lt;/DEALTIME&gt;&lt;OPTYPE&gt;REFUND&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;REFUND&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;Э6166047298&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;FASSAKHOVA/GULYANISA MS&lt;/FIO&gt;&lt;PASS&gt;PS6510973654&lt;/PASS&gt;&lt;BIRTH_DATE&gt;13091965&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;362&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;362&lt;/TCC&gt;&lt;SALEDATE&gt;25062011&lt;/SALEDATE&gt;&lt;SALETIME&gt;1258&lt;/SALET [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaRefund1 {
            get {
                return ResourceManager.GetString("SirenaRefund1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;ETICKET&lt;/TYPE&gt;&lt;CURRENCY&gt;РУБ&lt;/CURRENCY&gt;&lt;DEALDATE&gt;17052011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1706&lt;/DEALTIME&gt;&lt;OPTYPE&gt;REFUND&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;REFUND&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;Э6164537722&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;BLAGODER/VADIM MR&lt;/FIO&gt;&lt;PASS&gt;ПС0301161507&lt;/PASS&gt;&lt;BIRTH_DATE&gt;25031945&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;823&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;823&lt;/TCC&gt;&lt;SALEDATE&gt;17052011&lt;/SALEDATE&gt;&lt;SALETIME&gt;1040&lt;/SALETIME&gt;&lt;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaRefund2 {
            get {
                return ResourceManager.GetString("SirenaRefund2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;ETICKET&lt;/TYPE&gt;&lt;CURRENCY&gt;RUB&lt;/CURRENCY&gt;&lt;DEALDATE&gt;30062011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1300&lt;/DEALTIME&gt;&lt;OPTYPE&gt;SALE&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;SALE&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;Э6166223231&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;TISHIN/IGOR MR&lt;/FIO&gt;&lt;PASS&gt;PSP514894194&lt;/PASS&gt;&lt;BIRTH_DATE&gt;20101950&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;555&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;555&lt;/TCC&gt;&lt;SALEDATE&gt;&lt;/SALEDATE&gt;&lt;SALETIME&gt;&lt;/SALETIME&gt;&lt;RETTYPE&gt;0&lt;/RETTYPE&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaTicket1 {
            get {
                return ResourceManager.GetString("SirenaTicket1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;ETICKET&lt;/TYPE&gt;&lt;CURRENCY&gt;RUB&lt;/CURRENCY&gt;&lt;DEALDATE&gt;25062011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1258&lt;/DEALTIME&gt;&lt;OPTYPE&gt;SALE&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;SALE&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;Э6166047298&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;FASSAKHOVA/GULYANISA MS&lt;/FIO&gt;&lt;PASS&gt;PS6510973654&lt;/PASS&gt;&lt;BIRTH_DATE&gt;13091965&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;362&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;362&lt;/TCC&gt;&lt;SALEDATE&gt;&lt;/SALEDATE&gt;&lt;SALETIME&gt;&lt;/SALETIME&gt;&lt;RETTYPE&gt;0&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaTicket2 {
            get {
                return ResourceManager.GetString("SirenaTicket2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.6&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;ETICKET&lt;/TYPE&gt;&lt;CURRENCY&gt;RUB&lt;/CURRENCY&gt;&lt;DEALDATE&gt;14022011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1331&lt;/DEALTIME&gt;&lt;OPTYPE&gt;SALE&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;SALE&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;Э6162114281&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;DUBROV/VIACHESLAV MR&lt;/FIO&gt;&lt;PASS&gt;PSP710165564&lt;/PASS&gt;&lt;BIRTH_DATE&gt;17121988&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;298&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;298&lt;/TCC&gt;&lt;SALEDATE&gt;&lt;/SALEDATE&gt;&lt;SALETIME&gt;&lt;/SALETIME&gt;&lt;RETTYPE&gt;0&lt;/RET [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaTicket3 {
            get {
                return ResourceManager.GetString("SirenaTicket3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;ETICKET&lt;/TYPE&gt;&lt;CURRENCY&gt;РУБ&lt;/CURRENCY&gt;&lt;DEALDATE&gt;02052011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1517&lt;/DEALTIME&gt;&lt;OPTYPE&gt;SALE&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;SALE&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;Э6164098479&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;ТРОФИМЕНКО/АЛЕКСЕЙ Г-Н&lt;/FIO&gt;&lt;PASS&gt;ПС6005527605&lt;/PASS&gt;&lt;BIRTH_DATE&gt;19041983&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;95A&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;95A&lt;/TCC&gt;&lt;SALEDATE&gt;&lt;/SALEDATE&gt;&lt;SALETIME&gt;&lt;/SALETIME&gt;&lt;RETTYPE&gt;0&lt;/R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaTicket4 {
            get {
                return ResourceManager.GetString("SirenaTicket4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;ETICKET&lt;/TYPE&gt;&lt;CURRENCY&gt;РУБ&lt;/CURRENCY&gt;&lt;DEALDATE&gt;10052011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1837&lt;/DEALTIME&gt;&lt;OPTYPE&gt;SALE&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;SALE&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;Э6164310677&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;ZAYARNY/NIKOLAY MR&lt;/FIO&gt;&lt;PASS&gt;ПСП636755788&lt;/PASS&gt;&lt;BIRTH_DATE&gt;30071982&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;394&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;394&lt;/TCC&gt;&lt;SALEDATE&gt;&lt;/SALEDATE&gt;&lt;SALETIME&gt;&lt;/SALETIME&gt;&lt;RETTYPE&gt;0&lt;/RETTY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaTicket5 {
            get {
                return ResourceManager.GetString("SirenaTicket5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;TICKETS version=&quot;1.7&quot;&gt;&lt;TICKET&gt;&lt;TYPE&gt;ETICKET&lt;/TYPE&gt;&lt;CURRENCY&gt;РУБ&lt;/CURRENCY&gt;&lt;DEALDATE&gt;17052011&lt;/DEALDATE&gt;&lt;DEALTIME&gt;1040&lt;/DEALTIME&gt;&lt;OPTYPE&gt;SALE&lt;/OPTYPE&gt;&lt;TRANS_TYPE&gt;SALE&lt;/TRANS_TYPE&gt;&lt;MCO_TYPE&gt;&lt;/MCO_TYPE&gt;&lt;STAMP&gt;92390476&lt;/STAMP&gt;&lt;BSONUM&gt;Э6164537722&lt;/BSONUM&gt;&lt;EX_BSONUM&gt;&lt;/EX_BSONUM&gt;&lt;FIO&gt;BLAGODER/VADIM MR&lt;/FIO&gt;&lt;PASS&gt;ПС0301161507&lt;/PASS&gt;&lt;BIRTH_DATE&gt;25031945&lt;/BIRTH_DATE&gt;&lt;GENERAL_CARRIER&gt;823&lt;/GENERAL_CARRIER&gt;&lt;TCC&gt;823&lt;/TCC&gt;&lt;SALEDATE&gt;&lt;/SALEDATE&gt;&lt;SALETIME&gt;&lt;/SALETIME&gt;&lt;RETTYPE&gt;0&lt;/RETTYP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SirenaTicket6 {
            get {
                return ResourceManager.GetString("SirenaTicket6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;897&quot;,&quot;4400338913&quot;,&quot;5&quot;,76085,76085,&quot;17&quot;,&quot;&quot;,&quot;SALE&quot;,0,&quot;17&quot;,&quot;EVGEN&quot;,&quot;&quot;,&quot;&quot;,&quot;1589.00&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;210.1&quot;,&quot;190.6&quot;,&quot;132.4&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;AM&quot;,&quot;KC&quot;,&quot;YR&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;In&quot;,&quot;EVN&quot;,&quot;IEV&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;0124&quot;,0,&quot;���������� ��������� ��������,&quot;,1,0,&quot;&quot;,&quot;1.00&quot;,&quot;SHABLIIENKO/IU....
        /// </summary>
        internal static string TktBadTicket1 {
            get {
                return ResourceManager.GetString("TktBadTicket1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;870&quot;,&quot;4203245920&quot;,&quot;6&quot;,76175,0,&quot;&quot;,&quot;&quot;,&quot;SALE&quot;,0,&quot;10&quot;,&quot;INNA&quot;,&quot;&quot;,&quot;&quot;,&quot;1122.00&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;133.9&quot;,&quot;4.2&quot;,&quot;9.4&quot;,&quot;126.9&quot;,&quot;25.4&quot;,&quot;345&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0&quot;,&quot;CY&quot;,&quot;JW&quot;,&quot;JX&quot;,&quot;LB&quot;,&quot;VL&quot;,&quot;YQ&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;Ca&quot;,&quot;LCA&quot;,&quot;BEY&quot;,&quot;LCA&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;1&quot;,0,&quot;STREET&quot;,1,0,&quot;&quot;,&quot;9.00&quot;,&quot;TROINIKOVA/KATERYNA MISS*CHDDOB2&q....
        /// </summary>
        internal static string TktTicket1 {
            get {
                return ResourceManager.GetString("TktTicket1", resourceCulture);
            }
        }
    }
}
