//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxena.Travel.Bsv {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luxena.Travel.Bsv.ReportRes", typeof(ReportRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такси детальніше, ГРН:   .
        /// </summary>
        public static string FeesDetails {
            get {
                return ResourceManager.GetString("FeesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заборонено / DENIED.
        /// </summary>
        public static string TicketPrinter_ChangesNotAllowed {
            get {
                return ResourceManager.GetString("TicketPrinter_ChangesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штраф / CHARGE.
        /// </summary>
        public static string TicketPrinter_Charge {
            get {
                return ResourceManager.GetString("TicketPrinter_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если выполняется перевозка, в которой место окончательного назначения или остановка находятся не в стране отправления, к такой перевозке могут применяться положения Варшавской конвенции и эта Конвенция определяет и в большинстве случаев ограничивает ответственность перевозчиков в случае утери или повреждения товаров..
        /// </summary>
        public static string TicketPrinter_Footer {
            get {
                return ResourceManager.GetString("TicketPrinter_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без штрафу / NO CHARGE.
        /// </summary>
        public static string TicketPrinter_NoCharge {
            get {
                return ResourceManager.GetString("TicketPrinter_NoCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штраф 100% / Penalty 100%.
        /// </summary>
        public static string TicketPrinter_NoShowNotAllowed {
            get {
                return ResourceManager.GetString("TicketPrinter_NoShowNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без штрафу / FULL REF.
        /// </summary>
        public static string TicketPrinter_RefundNoCharge {
            get {
                return ResourceManager.GetString("TicketPrinter_RefundNoCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не повертається / NON REF.
        /// </summary>
        public static string TicketPrinter_RefundNotAllowed {
            get {
                return ResourceManager.GetString("TicketPrinter_RefundNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВИЛІТ:.
        /// </summary>
        public static string TicketPrinter_SegmentCaption {
            get {
                return ResourceManager.GetString("TicketPrinter_SegmentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Термінал.
        /// </summary>
        public static string TicketPrinter_Terminal {
            get {
                return ResourceManager.GetString("TicketPrinter_Terminal", resourceCulture);
            }
        }
    }
}
