//------------------------------------------------------------------------------
// <auto-generated>
// Res.cs
//
// Do not edit directly. This file has been generated by ResXPublicScriptGenerator v0.7.0.0.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

namespace Luxena.Travel {

	/// <summary>Res resources class</summary>
	[GeneratedCodeAttribute("ResXPublicScriptGenerator", "0.7.0.0")]
	[Resources]
	public static class Res {

		public static readonly string AviaDocuments = null;

		public static readonly string Menu_Dictionaries = null;

		public static readonly string Home = null;

		public static readonly string Parties = null;

		public static readonly string PartyType = null;

		public static readonly string PartyType_Text_List = null;

		public static readonly string Ticket = null;

		public static readonly string WorkItems_Title = null;

		public static readonly string User_Text_List = null;

		public static readonly string TicketDeleted = null;

		public static readonly string TicketEditForm_DiscountComPercent = null;

		public static readonly string TicketEditForm_DiscountSFPercent = null;

		public static readonly string Menu_Documents = null;

		public static readonly string AddPerson_Action_Title = null;

		public static readonly string Add_Action_Title = null;

		public static readonly string User_Active_Text = null;

		public static readonly string Confirmation = null;

		public static readonly string Password = null;

		public static readonly string Password_Error_Msg = null;

		public static readonly string GdsFile_Reimport_Text = null;

		public static readonly string Imported = null;

		public static readonly string User_AmadeusAirAgentId = null;

		public static readonly string User_AmadeusAirOfficeId = null;

		public static readonly string User_AmadeusPrintAgentId = null;

		public static readonly string User_AmadeusPrintOfficeId = null;

		public static readonly string User_GalileoMirAgentId = null;

		public static readonly string User_GalileoMirOfficeId = null;

		public static readonly string User_GalileoTktAgentId = null;

		public static readonly string User_GalileoTktOfficeId = null;

		public static readonly string CurrentUser_Caption = null;

		public static readonly string SignOut_Text = null;

		public static readonly string DocumentMetric_Date = null;

		public static readonly string DocumentMetric_Title_User = null;

		public static readonly string DocumentMetric_Issued = null;

		public static readonly string DocumentMetric_Unprocessed = null;

		public static readonly string FromDate_Text = null;

		public static readonly string ToDate_Text = null;

		public static readonly string DocumentMetric_TotalUnprocessedCount = null;

		public static readonly string DocumentMetricFilter_UnprocessedOnly = null;

		public static readonly string Apply_Text = null;

		public static readonly string Filter_Text = null;

		public static readonly string DocumentMetricTable_MaxRowCount_Msg = null;

		public static readonly string DocumentMetrics_DaysCount1 = null;

		public static readonly string DocumentMetrics_DaysCount2 = null;

		public static readonly string DocumentMetrics_DaysCount3 = null;

		public static readonly string DocumentMetrics_TotalDaysCount = null;

		public static readonly string DocumentMetrics_FromToDays_Text = null;

		public static readonly string Type = null;

		public static readonly string AviaDocument_Processed = null;

		public static readonly string AviaDocument_Unprocessed = null;

		public static readonly string AviaDocument_Voided = null;

		public static readonly string AviaDocument_Voidings = null;

		public static readonly string AviaDocument_AirlineFinanceData_Caption = null;

		public static readonly string Common_ServiceFeeData_Caption = null;

		public static readonly string Common_Vat_Text = null;

		public static readonly string AviaTicket_ReissueFor = null;

		public static readonly string AviaDocument_Handle_Action = null;

		public static readonly string AviaTicket_Handle_Title = null;

		public static readonly string FlightSegment_Arrival = null;

		public static readonly string FlightSegment_Departure = null;

		public static readonly string FlightSegment_Duration = null;

		public static readonly string FlightSegment_Registration = null;

		public static readonly string FlightSegment_Stops = null;

		public static readonly string Terminal_Text = null;

		public static readonly string Money_AmountFilter_Text = null;

		public static readonly string Money_CurrencyFilter_Text = null;

		public static readonly string UnloadApplication_Confirm_Msg = null;

		public static readonly string Menu_Administration = null;

		public static readonly string CalculateDiscount_Text = null;

		public static readonly string CalculateServiceFee_Text = null;

		public static readonly string AddDepartment_Action_Title = null;

		public static readonly string AddOrganization_Action_Title = null;

		public static readonly string SaveAndContinue = null;

		public static readonly string DocumentMetrics_NoData = null;

		public static readonly string CalculateRefundServiceFee_Text = null;

		public static readonly string CalculateServiceFeePenalty_Text = null;

		public static readonly string AviaMco_Handle_Title = null;

		public static readonly string AviaRefund_Handle_Title = null;

		public static readonly string DocumentMetrics_Report = null;

		public static readonly string ReservationTicketCount_Text = null;

		public static readonly string ProcessForm_ApplyToDocuments_Text = null;

		public static readonly string Menu_GetByNumber = null;

		public static readonly string EnterDocumentNumber_Text = null;

		public static readonly string Menu_FromList = null;

		public static readonly string Menu_MyUnprocessed = null;

		public static readonly string NoDocumentFound_Text = null;

		public static readonly string ReservationMcoCount_Text = null;

		public static readonly string ReservationRefundCount_Text = null;

		public static readonly string AddDocument_Title = null;

		public static readonly string SelectedDocuments_Title = null;

		public static readonly string AddedAviaDocumentFinanceData_Format = null;

		public static readonly string AddedAviaRefundFinanceData_Format = null;

		public static readonly string ReservationUnprocessedDocCount_Text = null;

		public static readonly string Void_Action = null;

		public static readonly string Restore_Action = null;

		public static readonly string Document_Restore_Confirmation1 = null;

		public static readonly string Document_Void_Confirmation1 = null;

		public static readonly string Document_Restore_Confirmation2 = null;

		public static readonly string Document_Restore_Confirmation3 = null;

		public static readonly string Document_Void_Confirmation2 = null;

		public static readonly string Document_Void_Confirmation3 = null;

		public static readonly string Document_RestoreDocuments_Msg = null;

		public static readonly string Document_RestoreDocument_Msg = null;

		public static readonly string Document_VoidDocuments_Msg = null;

		public static readonly string Document_VoidDocument_Msg = null;

		public static readonly string Common_CreateReport = null;

		public static readonly string CustomerReportForm_DocumentCount_Text = null;

		public static readonly string CustomerReportForm_IncludeDepartments1 = null;

		public static readonly string CustomerReportForm_IncludeDepartments2 = null;

		public static readonly string CustomerReportForm_IncludeDepartments3 = null;

		public static readonly string Document_Restore_Confirmation = null;

		public static readonly string Document_Void_Confirmation = null;

		public static readonly string TaskMetric_Title_User = null;

		public static readonly string TaskMetric_NoData = null;

		public static readonly string ViewDetails = null;

		public static readonly string Task_StatusChange_Msg = null;

		public static readonly string Task_StatusChange_Msg1 = null;

		public static readonly string Task_StatusChange_Msg2 = null;

		public static readonly string TaskMetric_Total = null;

		public static readonly string TaskIsClosed_Msg = null;

		public static readonly string TaskMetric_Total_Title = null;

		public static readonly string AviaDocument_AddRefund_Action = null;

		public static readonly string MoreActions = null;

		public static readonly string Cancel = null;

		public static readonly string OK = null;

		public static readonly string PrintReservation_Msg = null;

		public static readonly string PrintReservation_Msg_Title = null;

		public static readonly string AviaDocument_Print_Action = null;

		public static readonly string PersonEditForm_Emails = null;

		public static readonly string PersonEditForm_Phones = null;

		public static readonly string PersonEditForm_Female = null;

		public static readonly string PersonEditForm_Male = null;

		public static readonly string ApplyAirline_SelectDates_Text = null;

		public static readonly string ApplyAirline_Title = null;

		public static readonly string AirlineApplied_Msg1 = null;

		public static readonly string AirlineApplied_Msg2 = null;

		public static readonly string AirlineApplied_Msg3 = null;

		public static readonly string AirlineApplied_NotFound_Msg = null;

		public static readonly string ApplyAirline_Msg_Title = null;

		public static readonly string ApplyToDocuments_Text = null;

		public static readonly string ApplyServiceClass_Title = null;

		public static readonly string ServiceClassApplied_Msg1 = null;

		public static readonly string ServiceClassApplied_Msg2 = null;

		public static readonly string ServiceClassApplied_Msg3 = null;

		public static readonly string ApplyServiceClass_Msg_Title = null;

		public static readonly string ApplyGdsAgent_Msg_Title = null;

		public static readonly string ApplyGdsAgent_Title = null;

		public static readonly string GdsAgentApplied_Msg1 = null;

		public static readonly string GdsAgentApplied_Msg2 = null;

		public static readonly string GdsAgentApplied_Msg3 = null;

		public static readonly string GdsFile_Imported1 = null;

		public static readonly string GdsFile_Imported2 = null;

		public static readonly string GdsFile_Imported3 = null;

		public static readonly string AppliedDataToDocuments_Text1 = null;

		public static readonly string AppliedDataToDocuments_Text2 = null;

		public static readonly string AppliedDataToDocuments_Text3 = null;

		public static readonly string Profile_Item = null;

		public static readonly string Profile_Change_Password = null;

		public static readonly string Password_Edit = null;

		public static readonly string GdsAgents_NotAssigned = null;

		public static readonly string Password_ConfirmPassword = null;

		public static readonly string Password_NewPassword = null;

		public static readonly string Password_OldPassword = null;

		public static readonly string Password_Updated_Successfully = null;

		public static readonly string RegistryReportForm_Title = null;

		public static readonly string RegistryReport_Text = null;

		public static readonly string CustomerReport_Text = null;

		public static readonly string CustomerReportForm_Title = null;

		public static readonly string ImportAviaDocument_Msg = null;

		public static readonly string RestoreAviaDocument_Msg = null;

		public static readonly string VoidAviaDocument_Msg = null;

		public static readonly string NewTask_Msg = null;

		public static readonly string UserActiveStateChanged_Msg = null;

		public static readonly string UserRolesChanged_Msg = null;

		public static readonly string AviaDocument_Handle_NotFull = null;

		public static readonly string DocumentMetric_Title_Office = null;

		public static readonly string TaskMetric_Title_User_Office = null;

		public static readonly string ReportType_Text = null;

		public static readonly string FlightSegment_Caption = null;

		public static readonly string Clear = null;

		public static readonly string AviaDocument_NoNumber = null;

		public static readonly string AviaDocument_NotIssued = null;

		public static readonly string Common_ListNumber = null;

		public static readonly string Common_Measure_Items = null;

		public static readonly string Common_Quantity = null;

		public static readonly string Common_Price = null;

		public static readonly string OrderItem_Text = null;

		public static readonly string Order_IssueInvoice_Action = null;

		public static readonly string Order_IssueCompletionCertificate_Action = null;

		public static readonly string AviaDocument_AddToOrder = null;

		public static readonly string AviaDocument_AddToOrderExist = null;

		public static readonly string AviaDocument_AddToOrderNew = null;

		public static readonly string AviaDocument_Was_Added = null;

		public static readonly string Issued = null;

		public static readonly string Order_FinanceDataRecalculated = null;

		public static readonly string Order_RecalculateFinanceData = null;

		public static readonly string Order_GrandTotalWithoutVat = null;

		public static readonly string Common_QuantityShort = null;

		public static readonly string Menu_AddNew = null;

		public static readonly string OrderViewForm_Reservation = null;

		public static readonly string AviaDocumentProcessForm_Fare_Text = null;

		public static readonly string Order_Issue_NotValidData = null;

		public static readonly string Order_PaidAction = null;

		public static readonly string Order_PaidOrders_Msg = null;

		public static readonly string Order_PaidOrder_Msg = null;

		public static readonly string Order_UnPaidAction = null;

		public static readonly string Order_UnpaidOrders_Msg = null;

		public static readonly string Order_UnpaidOrder_Msg = null;

		public static readonly string Order_NotPaid = null;

		public static readonly string Order_Paid = null;

		public static readonly string Order_SeparateServiceFee = null;

		public static readonly string Menu_MyDocuments = null;

		public static readonly string OrderItem_WithoutVat = null;

		public static readonly string OrderItem_WithVat = null;

		public static readonly string AviaDocument_AddToOrder_Title = null;

		public static readonly string AviaDocument_CannotAddDocumentsToOrder_Msg = null;

		public static readonly string AviaDocument_ContinueAddToOrder_Msg = null;

		public static readonly string Order_DocumentAlreadyAddedToOrder_Msg = null;

		public static readonly string Order_Restore_Msg_Title = null;

		public static readonly string Order_Recalculation_Msg_Title = null;

		public static readonly string Order_SaveError_Msg = null;

		public static readonly string Order_SaveError_Msg_Title = null;

		public static readonly string CustomerReportForm_IncludeUnpayedDocumentOnly = null;

		public static readonly string Menu_WithSameAcquirer = null;

		public static readonly string Menu_AllMyDocuments = null;

		public static readonly string AviaTicket_AfterDeparture = null;

		public static readonly string AviaTicket_BeforeDeparture = null;

		public static readonly string Common_No = null;

		public static readonly string AviaTicket_ChangesPenalty = null;

		public static readonly string AviaTicket_NoShowPenalty = null;

		public static readonly string AviaTicket_RefundPenalty = null;

		public static readonly string AviaTicket_NoShowPenalty_Short = null;

		public static readonly string PenalizeOperationEditForm_Caption = null;

		public static readonly string AviaDocumentProcessForm_EditPenalizeOperations = null;

		public static readonly string Orders = null;

		public static readonly string AddObligation_Title = null;

		public static readonly string EnterObligationNumber_Text = null;

		public static readonly string Menu_IssuedByMe = null;

		public static readonly string Payment_AddValidDocuments_Msg = null;

		public static readonly string PaymentEditForm_AllObligationsCurrenciesError_Msg = null;

		public static readonly string Payment_AddObligation_Title = null;

		public static readonly string Payment_ObligationCurrenciesError_Msg = null;

		public static readonly string PaymentEditForm_PaymentCurrenciesError_Msg = null;

		public static readonly string Paid_Action_Text = null;

		public static readonly string Unpaid_Action_Text = null;

		public static readonly string PaymentCurrencyNotValid_Msg = null;

		public static readonly string PaymentEditForm_Total = null;

		public static readonly string Payment_Restore_Confirmation = null;

		public static readonly string Payment_Void_Confirmation = null;

		public static readonly string Payment_Voided = null;

		public static readonly string Order_AddToExistingPayment = null;

		public static readonly string Order_AddToNewPayment = null;

		public static readonly string Order_CreatePaymentAction = null;

		public static readonly string Order_NumberFormat1 = null;

		public static readonly string Order_NumberFormat2 = null;

		public static readonly string Order_NumberFormat3 = null;

		public static readonly string Payment_AddedToPayment_Msg1 = null;

		public static readonly string Payment_AddedToPayment_Msg11 = null;

		public static readonly string Payment_AddedToPayment_Msg2 = null;

		public static readonly string Payment_AddedToPayment_Msg3 = null;

		public static readonly string AviaDocumentList_CreateCashPayment = null;

		public static readonly string CashPaymentRegisterForm_Title = null;

		public static readonly string AviaDocumentList_CreatePayment_NotValidData = null;

		public static readonly string AviaDocumentList_AddToPayment = null;

		public static readonly string AviaDocumentList_CannotCreatePayment = null;

		public static readonly string AviaDocumentList_CreateCashPayment_Title = null;

		public static readonly string Common_Document = null;

		public static readonly string Posted_Action = null;

		public static readonly string PaymentList_PostedDocuments = null;

		public static readonly string Payment_NonPosted = null;

		public static readonly string PaymentView_Posted = null;

		public static readonly string CongradulationText = null;

		public static readonly string CalculateHandling_Text = null;

		public static readonly string Order_NoPayments = null;

		public static readonly string Order_AlreadyPaid = null;

		public static readonly string PaymentVoidForm_Title = null;

		public static readonly string PaymentVoidForm_VoidButton = null;

		public static readonly string AviaDocument_CalculateFare = null;

		public static readonly string AviaDocument_CalculateFeesTotal = null;

		public static readonly string AviaDocument_CalculateCancelFee = null;

		public static readonly string Order_PayMenu = null;

		public static readonly string DocumentMetric_ToIssue = null;

		public static readonly string AddAction = null;

		public static readonly string Order_AddIssue_Action = null;

		public static readonly string File_UploadAction = null;

		public static readonly string File_WaitUpload = null;

		public static readonly string Close_Action = null;

		public static readonly string Order_PostedPaymentInOrder_Msg = null;

		public static readonly string Order_Void_Msg_Title = null;

		public static readonly string File_Upload_Failed = null;

		public static readonly string File_Upload_Success = null;

		public static readonly string File_Deleted = null;

		public static readonly string Add = null;

		public static readonly string ClosedPeriod_Overlap = null;

		public static readonly string Order_DoSweep_Msg = null;

		public static readonly string Order_Sweep_Action = null;

		public static readonly string Order_Sweep_Done = null;

		public static readonly string AviaTicket_PassengerInfoError_Msg = null;

		public static readonly string AddPassenger_Action_Title = null;

		public static readonly string AddPassport_Action_Title = null;

		public static readonly string Use_Gds_Passport_Action_Title = null;

		public static readonly string Use_System_Passport_Action_Title = null;

		public static readonly string Passenger_NoPassport_Warning = null;

		public static readonly string Passenger_PassportDataDoesntMatch_Warning = null;

		public static readonly string ChangePassport_Action_Title = null;

		public static readonly string Passenger_NoGdsPassport_Warning = null;

		public static readonly string Passenger_PassportExpired_Warning = null;

		public static readonly string AviaTicket_PassengerPassportRequired = null;

		public static readonly string DocumentMetric_IncorrectPassport = null;

		public static readonly string DocumentMetric_NoPassport = null;

		public static readonly string DocumentMetric_PassportProblem = null;

		public static readonly string AviaDocumentProcessForm_CopyPassportGdsString = null;

		public static readonly string DocumentMetric_Urgent = null;

		public static readonly string SetPassengerAsCustomer_Action_Title = null;

		public static readonly string Passport_List_Title = null;

		public static readonly string Passport_PrivateData = null;

		public static readonly string Gender_Female = null;

		public static readonly string Gender_Male = null;

		public static readonly string Passport_IssuedBy = null;

		public static readonly string SetPassenger_Action_Title = null;

		public static readonly string Mar8Congratulations = null;

		public static readonly string PassportCompare_Caption = null;

		public static readonly string PassportCompare_GdsPassport = null;

		public static readonly string PassportCompare_PersonPassport = null;

		public static readonly string PassportCompare_UseGdsPassport = null;

		public static readonly string PassportCompare_UsePersonPassport = null;

		public static readonly string ComparePassports = null;

		public static readonly string CalculateCommissionDiscount_Text = null;

		public static readonly string CashPaymentRegisterForm_DoCreateConsignment = null;

		public static readonly string Menu_Reports = null;

		public static readonly string AddConsignmentItems_Title = null;

		public static readonly string EnterInvoiceNumber_Text = null;

		public static readonly string IssueConsignmentAction = null;

		public static readonly string Issued_Consignment = null;

		public static readonly string Menu_GetByOrderNumber = null;

		public static readonly string NoInvoiceFound_Text = null;

		public static readonly string InvoiceItemsInConsignments_Warn = null;

		public static readonly string IssueInvoice_Title = null;

		public static readonly string IssueCompletionCertificate_Title = null;

		public static readonly string Invoice_IssueDate = null;

		public static readonly string Auto = null;

		public static readonly string Issue = null;

		public static readonly string InvoiceIssued_Msg = null;

		public static readonly string PrintedInvoice_Text = null;

		public static readonly string Invoice_Reissue = null;

		public static readonly string Order_IssueReceipt_Action = null;

		public static readonly string CashInOrderPayment_DocumentName = null;

		public static readonly string CashOutOrderPayment_DocumentName = null;

		public static readonly string CheckPayment_DocumentName = null;

		public static readonly string WireTransfer_DocumentName = null;

		public static readonly string Payment_CreateCashInOrder_Action = null;

		public static readonly string Payment_CreateCashOutOrder_Action = null;

		public static readonly string Payment_CreateCheckPayment_Action = null;

		public static readonly string Payment_CreateNonCashPayment_Action = null;

		public static readonly string Payment_CreatePayment_Action = null;

		public static readonly string CashInOrderPayment_SavePosted = null;

		public static readonly string OrderView_IssuedInvoice_Html = null;

		public static readonly string OrderItems = null;

		public static readonly string Payments = null;

		public static readonly string CashInOrderPayment_DocumentName_Format = null;

		public static readonly string CashOutOrderPayment_DocumentName_Format = null;

		public static readonly string CheckPayment_DocumentName_Format = null;

		public static readonly string WireTransfer_DocumentName_Format = null;

		public static readonly string ReceiptIssued_Msg = null;

		public static readonly string NewOrder_Action = null;

		public static readonly string QuickReceipt_Action = null;

		public static readonly string NewTask_Action = null;

		public static readonly string QuickReceipt_AviaTickets = null;

		public static readonly string QuickReceipt_Title = null;

		public static readonly string Create = null;

		public static readonly string QuickReceipt_Created_Msg = null;

		public static readonly string QuickCashPayment_Consiment_Msg = null;

		public static readonly string QuickCashPayment_Msg = null;

		public static readonly string PaymentView_Document = null;

		public static readonly string OrderStatusChange_Action = null;

		public static readonly string OrderStatusChange_Msg = null;

		public static readonly string OrderStatusChange_Title = null;

		public static readonly string Invoice_List = null;

		public static readonly string QuickReceipt_ServiceFee = null;

		public static readonly string Payment_Invoice = null;

		public static readonly string OrderStatusChange_Msg_Short = null;

		public static readonly string Order_CannotRestoreOrder_Msg = null;

		public static readonly string Overpay = null;

		public static readonly string Payment_CreateElecronicPayment_Action = null;

		public static readonly string PersonView_Personal_Info = null;

		public static readonly string ElectronicPayment_DocumentName = null;

		public static readonly string ElectronicPayment_DocumentName_Format = null;

		public static readonly string Payment_DocumentNumber = null;

		public static readonly string AviaDocumentProcessForm_CustomerChanged = null;

		public static readonly string PartyView_Confirm_File_Delete = null;

		public static readonly string Invoice_Deleted_Message = null;

		public static readonly string Invoice_Delete_Confirmation = null;

		public static readonly string Receipt_Deleted_Message = null;

		public static readonly string Receipt_Delete_Confirmation = null;

		public static readonly string OrganizationView_Info = null;

		public static readonly string FileUpload_Title = null;

		public static readonly string DepartmentView_Info = null;

		public static readonly string OrderView_IsNotPublic = null;

		public static readonly string OrderView_IsPublic = null;

		public static readonly string ApplicationVersionChanged = null;

		public static readonly string Attention = null;

		public static readonly string AviaDocument_Blank_Action = null;

		public static readonly string UnbalancedReportForm_IncludeOrders = null;

		public static readonly string UnbalancedReport = null;

		public static readonly string Task_Add = null;

		public static readonly string TaskStatusChanged_Msg = null;

		public static readonly string Apply = null;

		public static readonly string HomeSettingsForm_Reports = null;

		public static readonly string HomeSettingsForm_IntervalTooBig = null;

		public static readonly string HomeSettingsForm_IntervalTooSmall = null;

		public static readonly string HomeSettingsForm_Title = null;

		public static readonly string InvoiceIssueForm_ShowPaid = null;

		public static readonly string Payment_CreateInternalTransfer_Action = null;

		public static readonly string UpdateAnalytics_Action = null;

		public static readonly string UpdateAnalytics_Info = null;

		public static readonly string UpdateAnalytics_Success = null;

		public static readonly string UpdateAnalytics_Error = null;

		public static readonly string AviaConsoleParser_Action = null;

		public static readonly string AviaConsoleParserForm_Title = null;

		public static readonly string AviaConsoleParserForm_Label1 = null;
		public static readonly string AviaConsoleParserForm_Label2 = null;
		public static readonly string AviaConsoleParserForm_Label3 = null;

		public static readonly string AviaConsoleParserForm_Parse = null;

	}
}
