//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxena.Travel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luxena.Travel.CommonRes", typeof(CommonRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллиардов.
        /// </summary>
        public static string Billion_Five {
            get {
                return ResourceManager.GetString("Billion_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллиард.
        /// </summary>
        public static string Billion_One {
            get {
                return ResourceManager.GetString("Billion_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллиарда.
        /// </summary>
        public static string Billion_Two {
            get {
                return ResourceManager.GetString("Billion_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравить с Днем рождения.
        /// </summary>
        public static string BirthdayTask_Subject {
            get {
                return ResourceManager.GetString("BirthdayTask_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дн. назад.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восемь.
        /// </summary>
        public static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восемнадцать.
        /// </summary>
        public static string Eighteen {
            get {
                return ResourceManager.GetString("Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восемьсот.
        /// </summary>
        public static string EightHundred {
            get {
                return ResourceManager.GetString("EightHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восемьдеся.
        /// </summary>
        public static string Eighty {
            get {
                return ResourceManager.GetString("Eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одиннадцать.
        /// </summary>
        public static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пятнадцать.
        /// </summary>
        public static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пятьдесят.
        /// </summary>
        public static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пять.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пятьсот.
        /// </summary>
        public static string FiveHundred {
            get {
                return ResourceManager.GetString("FiveHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сорок.
        /// </summary>
        public static string Forty {
            get {
                return ResourceManager.GetString("Forty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to четыре.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to четыреста.
        /// </summary>
        public static string FourHundred {
            get {
                return ResourceManager.GetString("FourHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to четырнадцать.
        /// </summary>
        public static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сто.
        /// </summary>
        public static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} успешно импортирован.
        /// </summary>
        public static string ImportGdsFiles_DocumentImported {
            get {
                return ResourceManager.GetString("ImportGdsFiles_DocumentImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллионов.
        /// </summary>
        public static string Million_Five {
            get {
                return ResourceManager.GetString("Million_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллион.
        /// </summary>
        public static string Million_One {
            get {
                return ResourceManager.GetString("Million_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллиона.
        /// </summary>
        public static string Million_Two {
            get {
                return ResourceManager.GetString("Million_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to минус.
        /// </summary>
        public static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to девять.
        /// </summary>
        public static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to девятьсот.
        /// </summary>
        public static string NineHundred {
            get {
                return ResourceManager.GetString("NineHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to девятнадцать.
        /// </summary>
        public static string Nineteen {
            get {
                return ResourceManager.GetString("Nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to девяносто.
        /// </summary>
        public static string Ninety {
            get {
                return ResourceManager.GetString("Ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        public static string Number_Short {
            get {
                return ResourceManager.GetString("Number_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to один.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одна.
        /// </summary>
        public static string One1 {
            get {
                return ResourceManager.GetString("One1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одно.
        /// </summary>
        public static string One2 {
            get {
                return ResourceManager.GetString("One2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата проживания.
        /// </summary>
        public static string OrderItem_AccommodationSource {
            get {
                return ResourceManager.GetString("OrderItem_AccommodationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата авиадокумента.
        /// </summary>
        public static string OrderItem_AviaMcoSource {
            get {
                return ResourceManager.GetString("OrderItem_AviaMcoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат авиабилета.
        /// </summary>
        public static string OrderItem_AviaRefundSource {
            get {
                return ResourceManager.GetString("OrderItem_AviaRefundSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервисный сбор.
        /// </summary>
        public static string OrderItem_AviaServiceFeeSource {
            get {
                return ResourceManager.GetString("OrderItem_AviaServiceFeeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата авиабилета.
        /// </summary>
        public static string OrderItem_AviaTicketSource {
            get {
                return ResourceManager.GetString("OrderItem_AviaTicketSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата авиабилетов.
        /// </summary>
        public static string OrderItem_AviaTicketsSource {
            get {
                return ResourceManager.GetString("OrderItem_AviaTicketsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to место.
        /// </summary>
        public static string OrderItem_BusTicketSource_SeatNumber {
            get {
                return ResourceManager.GetString("OrderItem_BusTicketSource_SeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата аренды авто.
        /// </summary>
        public static string OrderItem_CarRentalSource {
            get {
                return ResourceManager.GetString("OrderItem_CarRentalSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата экскурсии.
        /// </summary>
        public static string OrderItem_ExcursionSource {
            get {
                return ResourceManager.GetString("OrderItem_ExcursionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string OrderItem_From {
            get {
                return ResourceManager.GetString("OrderItem_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата услуги .
        /// </summary>
        public static string OrderItem_GenericProduct {
            get {
                return ResourceManager.GetString("OrderItem_GenericProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата страховки.
        /// </summary>
        public static string OrderItem_InsuranceSource {
            get {
                return ResourceManager.GetString("OrderItem_InsuranceSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата студенческого билета ISIC.
        /// </summary>
        public static string OrderItem_IsicSource {
            get {
                return ResourceManager.GetString("OrderItem_IsicSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата железнодорожного билета.
        /// </summary>
        public static string OrderItem_PasteboardSource {
            get {
                return ResourceManager.GetString("OrderItem_PasteboardSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вагон.
        /// </summary>
        public static string OrderItem_PasteboardSource_CarNumber {
            get {
                return ResourceManager.GetString("OrderItem_PasteboardSource_CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дата отправления.
        /// </summary>
        public static string OrderItem_PasteboardSource_StartDate {
            get {
                return ResourceManager.GetString("OrderItem_PasteboardSource_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поезд.
        /// </summary>
        public static string OrderItem_PasteboardSource_TrainNumber {
            get {
                return ResourceManager.GetString("OrderItem_PasteboardSource_TrainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата SIM-карты.
        /// </summary>
        public static string OrderItem_SimCardSource {
            get {
                return ResourceManager.GetString("OrderItem_SimCardSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата готового тура.
        /// </summary>
        public static string OrderItem_TourSource {
            get {
                return ResourceManager.GetString("OrderItem_TourSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата трансфера.
        /// </summary>
        public static string OrderItem_TransferSource {
            get {
                return ResourceManager.GetString("OrderItem_TransferSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восстановлен.
        /// </summary>
        public static string Restored {
            get {
                return ResourceManager.GetString("Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рублей.
        /// </summary>
        public static string RUB_Five {
            get {
                return ResourceManager.GetString("RUB_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to коп..
        /// </summary>
        public static string RUB_Minor_Five {
            get {
                return ResourceManager.GetString("RUB_Minor_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to коп..
        /// </summary>
        public static string RUB_Minor_One {
            get {
                return ResourceManager.GetString("RUB_Minor_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to коп..
        /// </summary>
        public static string RUB_Minor_Two {
            get {
                return ResourceManager.GetString("RUB_Minor_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рубль.
        /// </summary>
        public static string RUB_One {
            get {
                return ResourceManager.GetString("RUB_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рубля.
        /// </summary>
        public static string RUB_Two {
            get {
                return ResourceManager.GetString("RUB_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to семь.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to семьсот.
        /// </summary>
        public static string SevenHundred {
            get {
                return ResourceManager.GetString("SevenHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to семнадцать.
        /// </summary>
        public static string Seventeen {
            get {
                return ResourceManager.GetString("Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to семьдесят.
        /// </summary>
        public static string Seventy {
            get {
                return ResourceManager.GetString("Seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шесть.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шестьсот.
        /// </summary>
        public static string SixHundred {
            get {
                return ResourceManager.GetString("SixHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шестнадцать.
        /// </summary>
        public static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шестьдесят.
        /// </summary>
        public static string Sixty {
            get {
                return ResourceManager.GetString("Sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to десять.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тринадцать.
        /// </summary>
        public static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тридцать.
        /// </summary>
        public static string Thirty {
            get {
                return ResourceManager.GetString("Thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тысяч.
        /// </summary>
        public static string Thousand_Five {
            get {
                return ResourceManager.GetString("Thousand_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тысяча.
        /// </summary>
        public static string Thousand_One {
            get {
                return ResourceManager.GetString("Thousand_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тысячи.
        /// </summary>
        public static string Thousand_Two {
            get {
                return ResourceManager.GetString("Thousand_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to три.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to триста.
        /// </summary>
        public static string ThreeHundred {
            get {
                return ResourceManager.GetString("ThreeHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to завтра.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to двенадцать.
        /// </summary>
        public static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to двадцать.
        /// </summary>
        public static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to два.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to две.
        /// </summary>
        public static string Two1 {
            get {
                return ResourceManager.GetString("Two1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to два.
        /// </summary>
        public static string Two2 {
            get {
                return ResourceManager.GetString("Two2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to двести.
        /// </summary>
        public static string TwoHundred {
            get {
                return ResourceManager.GetString("TwoHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гривен.
        /// </summary>
        public static string UAH_Five {
            get {
                return ResourceManager.GetString("UAH_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to коп..
        /// </summary>
        public static string UAH_Minor_Five {
            get {
                return ResourceManager.GetString("UAH_Minor_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to коп..
        /// </summary>
        public static string UAH_Minor_One {
            get {
                return ResourceManager.GetString("UAH_Minor_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to коп..
        /// </summary>
        public static string UAH_Minor_Two {
            get {
                return ResourceManager.GetString("UAH_Minor_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гривна.
        /// </summary>
        public static string UAH_One {
            get {
                return ResourceManager.GetString("UAH_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гривны.
        /// </summary>
        public static string UAH_Two {
            get {
                return ResourceManager.GetString("UAH_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аннулирован.
        /// </summary>
        public static string Voided {
            get {
                return ResourceManager.GetString("Voided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вчера.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
