//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxena.Travel.TravelPointWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://46.4.91.251", ConfigurationName="TravelPointWebService.ImportServiceXMLPortType")]
    public interface ImportServiceXMLPortType {
        
        // CODEGEN: Generating message contract since element name office_id from namespace http://46.4.91.251 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://46.4.91.251#ImportServiceXML:Import", ReplyAction="*")]
        Luxena.Travel.TravelPointWebService.ImportResponse Import(Luxena.Travel.TravelPointWebService.ImportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://46.4.91.251#ImportServiceXML:Import", ReplyAction="*")]
        System.Threading.Tasks.Task<Luxena.Travel.TravelPointWebService.ImportResponse> ImportAsync(Luxena.Travel.TravelPointWebService.ImportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Import", Namespace="http://46.4.91.251", Order=0)]
        public Luxena.Travel.TravelPointWebService.ImportRequestBody Body;
        
        public ImportRequest() {
        }
        
        public ImportRequest(Luxena.Travel.TravelPointWebService.ImportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://46.4.91.251")]
    public partial class ImportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string office_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string startdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string enddate;
        
        public ImportRequestBody() {
        }
        
        public ImportRequestBody(string office_id, string startdate, string enddate) {
            this.office_id = office_id;
            this.startdate = startdate;
            this.enddate = enddate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportResponse", Namespace="http://46.4.91.251", Order=0)]
        public Luxena.Travel.TravelPointWebService.ImportResponseBody Body;
        
        public ImportResponse() {
        }
        
        public ImportResponse(Luxena.Travel.TravelPointWebService.ImportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://46.4.91.251")]
    public partial class ImportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ImportResponseBody() {
        }
        
        public ImportResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImportServiceXMLPortTypeChannel : Luxena.Travel.TravelPointWebService.ImportServiceXMLPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportServiceXMLPortTypeClient : System.ServiceModel.ClientBase<Luxena.Travel.TravelPointWebService.ImportServiceXMLPortType>, Luxena.Travel.TravelPointWebService.ImportServiceXMLPortType {
        
        public ImportServiceXMLPortTypeClient() {
        }
        
        public ImportServiceXMLPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportServiceXMLPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceXMLPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceXMLPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Luxena.Travel.TravelPointWebService.ImportResponse Luxena.Travel.TravelPointWebService.ImportServiceXMLPortType.Import(Luxena.Travel.TravelPointWebService.ImportRequest request) {
            return base.Channel.Import(request);
        }
        
        public string Import(string office_id, string startdate, string enddate) {
            Luxena.Travel.TravelPointWebService.ImportRequest inValue = new Luxena.Travel.TravelPointWebService.ImportRequest();
            inValue.Body = new Luxena.Travel.TravelPointWebService.ImportRequestBody();
            inValue.Body.office_id = office_id;
            inValue.Body.startdate = startdate;
            inValue.Body.enddate = enddate;
            Luxena.Travel.TravelPointWebService.ImportResponse retVal = ((Luxena.Travel.TravelPointWebService.ImportServiceXMLPortType)(this)).Import(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Luxena.Travel.TravelPointWebService.ImportResponse> Luxena.Travel.TravelPointWebService.ImportServiceXMLPortType.ImportAsync(Luxena.Travel.TravelPointWebService.ImportRequest request) {
            return base.Channel.ImportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Luxena.Travel.TravelPointWebService.ImportResponse> ImportAsync(string office_id, string startdate, string enddate) {
            Luxena.Travel.TravelPointWebService.ImportRequest inValue = new Luxena.Travel.TravelPointWebService.ImportRequest();
            inValue.Body = new Luxena.Travel.TravelPointWebService.ImportRequestBody();
            inValue.Body.office_id = office_id;
            inValue.Body.startdate = startdate;
            inValue.Body.enddate = enddate;
            return ((Luxena.Travel.TravelPointWebService.ImportServiceXMLPortType)(this)).ImportAsync(inValue);
        }
    }
}
