using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18047
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("Luxena Company")]
[assembly: AssemblyProductAttribute("Luxena.Travel")]
[assembly: AssemblyCopyrightAttribute("Copyright Luxena Company 2001-2013")]
[assembly: AssemblyVersionAttribute("1.0.0.38890")]

