//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxena.Travel.GalileoWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GalileoWebService.XMLWebServiceSoap")]
    public interface XMLWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketsXML", ReplyAction="*")]
        Luxena.Travel.GalileoWebService.GetTicketsXMLResponse GetTicketsXML(Luxena.Travel.GalileoWebService.GetTicketsXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketsXML", ReplyAction="*")]
        System.Threading.Tasks.Task<Luxena.Travel.GalileoWebService.GetTicketsXMLResponse> GetTicketsXMLAsync(Luxena.Travel.GalileoWebService.GetTicketsXMLRequest request);
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketsXMLByPeriod", ReplyAction="*")]
        Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodResponse GetTicketsXMLByPeriod(Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketsXMLByPeriod", ReplyAction="*")]
        System.Threading.Tasks.Task<Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodResponse> GetTicketsXMLByPeriodAsync(Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketsXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketsXML", Namespace="http://tempuri.org/", Order=0)]
        public Luxena.Travel.GalileoWebService.GetTicketsXMLRequestBody Body;
        
        public GetTicketsXMLRequest() {
        }
        
        public GetTicketsXMLRequest(Luxena.Travel.GalileoWebService.GetTicketsXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketsXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iDays;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sTicketingAgency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sBookingAgency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sDocType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sSubagent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sFormOfPayment;
        
        public GetTicketsXMLRequestBody() {
        }
        
        public GetTicketsXMLRequestBody(string sUserName, string sPassword, int iDays, string sTicketingAgency, string sBookingAgency, string sDocType, string sSubagent, string sFormOfPayment) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.iDays = iDays;
            this.sTicketingAgency = sTicketingAgency;
            this.sBookingAgency = sBookingAgency;
            this.sDocType = sDocType;
            this.sSubagent = sSubagent;
            this.sFormOfPayment = sFormOfPayment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketsXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketsXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Luxena.Travel.GalileoWebService.GetTicketsXMLResponseBody Body;
        
        public GetTicketsXMLResponse() {
        }
        
        public GetTicketsXMLResponse(Luxena.Travel.GalileoWebService.GetTicketsXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketsXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTicketsXMLResult;
        
        public GetTicketsXMLResponseBody() {
        }
        
        public GetTicketsXMLResponseBody(string GetTicketsXMLResult) {
            this.GetTicketsXMLResult = GetTicketsXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketsXMLByPeriodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketsXMLByPeriod", Namespace="http://tempuri.org/", Order=0)]
        public Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequestBody Body;
        
        public GetTicketsXMLByPeriodRequest() {
        }
        
        public GetTicketsXMLByPeriodRequest(Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketsXMLByPeriodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sDates;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sDays;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sTicketingAgency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sBookingAgency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sDocType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sSubagent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sFormOfPayment;
        
        public GetTicketsXMLByPeriodRequestBody() {
        }
        
        public GetTicketsXMLByPeriodRequestBody(string sUserName, string sPassword, string sDates, string sDays, string sTicketingAgency, string sBookingAgency, string sDocType, string sSubagent, string sFormOfPayment) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sDates = sDates;
            this.sDays = sDays;
            this.sTicketingAgency = sTicketingAgency;
            this.sBookingAgency = sBookingAgency;
            this.sDocType = sDocType;
            this.sSubagent = sSubagent;
            this.sFormOfPayment = sFormOfPayment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketsXMLByPeriodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketsXMLByPeriodResponse", Namespace="http://tempuri.org/", Order=0)]
        public Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodResponseBody Body;
        
        public GetTicketsXMLByPeriodResponse() {
        }
        
        public GetTicketsXMLByPeriodResponse(Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketsXMLByPeriodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTicketsXMLByPeriodResult;
        
        public GetTicketsXMLByPeriodResponseBody() {
        }
        
        public GetTicketsXMLByPeriodResponseBody(string GetTicketsXMLByPeriodResult) {
            this.GetTicketsXMLByPeriodResult = GetTicketsXMLByPeriodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XMLWebServiceSoapChannel : Luxena.Travel.GalileoWebService.XMLWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLWebServiceSoapClient : System.ServiceModel.ClientBase<Luxena.Travel.GalileoWebService.XMLWebServiceSoap>, Luxena.Travel.GalileoWebService.XMLWebServiceSoap {
        
        public XMLWebServiceSoapClient() {
        }
        
        public XMLWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Luxena.Travel.GalileoWebService.GetTicketsXMLResponse Luxena.Travel.GalileoWebService.XMLWebServiceSoap.GetTicketsXML(Luxena.Travel.GalileoWebService.GetTicketsXMLRequest request) {
            return base.Channel.GetTicketsXML(request);
        }
        
        public string GetTicketsXML(string sUserName, string sPassword, int iDays, string sTicketingAgency, string sBookingAgency, string sDocType, string sSubagent, string sFormOfPayment) {
            Luxena.Travel.GalileoWebService.GetTicketsXMLRequest inValue = new Luxena.Travel.GalileoWebService.GetTicketsXMLRequest();
            inValue.Body = new Luxena.Travel.GalileoWebService.GetTicketsXMLRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.iDays = iDays;
            inValue.Body.sTicketingAgency = sTicketingAgency;
            inValue.Body.sBookingAgency = sBookingAgency;
            inValue.Body.sDocType = sDocType;
            inValue.Body.sSubagent = sSubagent;
            inValue.Body.sFormOfPayment = sFormOfPayment;
            Luxena.Travel.GalileoWebService.GetTicketsXMLResponse retVal = ((Luxena.Travel.GalileoWebService.XMLWebServiceSoap)(this)).GetTicketsXML(inValue);
            return retVal.Body.GetTicketsXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Luxena.Travel.GalileoWebService.GetTicketsXMLResponse> Luxena.Travel.GalileoWebService.XMLWebServiceSoap.GetTicketsXMLAsync(Luxena.Travel.GalileoWebService.GetTicketsXMLRequest request) {
            return base.Channel.GetTicketsXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Luxena.Travel.GalileoWebService.GetTicketsXMLResponse> GetTicketsXMLAsync(string sUserName, string sPassword, int iDays, string sTicketingAgency, string sBookingAgency, string sDocType, string sSubagent, string sFormOfPayment) {
            Luxena.Travel.GalileoWebService.GetTicketsXMLRequest inValue = new Luxena.Travel.GalileoWebService.GetTicketsXMLRequest();
            inValue.Body = new Luxena.Travel.GalileoWebService.GetTicketsXMLRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.iDays = iDays;
            inValue.Body.sTicketingAgency = sTicketingAgency;
            inValue.Body.sBookingAgency = sBookingAgency;
            inValue.Body.sDocType = sDocType;
            inValue.Body.sSubagent = sSubagent;
            inValue.Body.sFormOfPayment = sFormOfPayment;
            return ((Luxena.Travel.GalileoWebService.XMLWebServiceSoap)(this)).GetTicketsXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodResponse Luxena.Travel.GalileoWebService.XMLWebServiceSoap.GetTicketsXMLByPeriod(Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequest request) {
            return base.Channel.GetTicketsXMLByPeriod(request);
        }
        
        public string GetTicketsXMLByPeriod(string sUserName, string sPassword, string sDates, string sDays, string sTicketingAgency, string sBookingAgency, string sDocType, string sSubagent, string sFormOfPayment) {
            Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequest inValue = new Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequest();
            inValue.Body = new Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sDates = sDates;
            inValue.Body.sDays = sDays;
            inValue.Body.sTicketingAgency = sTicketingAgency;
            inValue.Body.sBookingAgency = sBookingAgency;
            inValue.Body.sDocType = sDocType;
            inValue.Body.sSubagent = sSubagent;
            inValue.Body.sFormOfPayment = sFormOfPayment;
            Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodResponse retVal = ((Luxena.Travel.GalileoWebService.XMLWebServiceSoap)(this)).GetTicketsXMLByPeriod(inValue);
            return retVal.Body.GetTicketsXMLByPeriodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodResponse> Luxena.Travel.GalileoWebService.XMLWebServiceSoap.GetTicketsXMLByPeriodAsync(Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequest request) {
            return base.Channel.GetTicketsXMLByPeriodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodResponse> GetTicketsXMLByPeriodAsync(string sUserName, string sPassword, string sDates, string sDays, string sTicketingAgency, string sBookingAgency, string sDocType, string sSubagent, string sFormOfPayment) {
            Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequest inValue = new Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequest();
            inValue.Body = new Luxena.Travel.GalileoWebService.GetTicketsXMLByPeriodRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sDates = sDates;
            inValue.Body.sDays = sDays;
            inValue.Body.sTicketingAgency = sTicketingAgency;
            inValue.Body.sBookingAgency = sBookingAgency;
            inValue.Body.sDocType = sDocType;
            inValue.Body.sSubagent = sSubagent;
            inValue.Body.sFormOfPayment = sFormOfPayment;
            return ((Luxena.Travel.GalileoWebService.XMLWebServiceSoap)(this)).GetTicketsXMLByPeriodAsync(inValue);
        }
    }
}
